/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        bg:         'var(--bg)',
        surface: {
          DEFAULT: 'var(--surface)',
          1:       'var(--surface)',
          2:       'var(--surface-2)',
          3:       'var(--surface-3)',
        },
        'surface-1': 'var(--surface)',
        'surface-2': 'var(--surface-2)',
        'surface-3': 'var(--surface-3)',
        border:     'var(--border)',
        'border-2': 'var(--border-2)',
        'border-3': 'var(--border-3)',
        'border-strong': 'var(--border-3)',
        fg:         'var(--text)',
        text:       'var(--text)',
        muted:      'var(--text-muted)',
        'fg-muted': 'var(--text-muted)',
        'text-muted':'var(--text-muted)',
        dim:        'var(--text-dim)',
        'fg-subtle':'var(--text-dim)',
        'text-dim': 'var(--text-dim)',
        primary: {
          DEFAULT: 'var(--primary)',
          2:       'var(--primary-2)',
          soft:    'var(--primary-soft)',
          glow:    'var(--primary-glow)',
          hover:   '#8E73FF',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          soft:    'var(--accent-soft)',
          glow:    'var(--accent-glow)',
        },
        success: {
          DEFAULT: 'var(--success)',
          soft:    'var(--success-soft)',
          hover:   '#4ADE94',
        },
        warning: {
          DEFAULT: 'var(--warning)',
          soft:    'var(--warning-soft)',
          hover:   '#FCC54A',
        },
        danger: {
          DEFAULT: 'var(--danger)',
          soft:    'var(--danger-soft)',
          hover:   '#FB8B8B',
        },
        info: { DEFAULT: 'var(--info)', soft: 'var(--info-soft)' },
        pink: { DEFAULT: 'var(--pink)', soft: 'var(--pink-soft)' },
        lime: { DEFAULT: 'var(--lime)', soft: 'var(--lime-soft)' },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        'xs': 'var(--radius-sm)',
        sm:   'var(--radius-sm)',
        DEFAULT: 'var(--radius)',
        md:   'var(--radius-md)',
        lg:   'var(--radius-lg)',
        xl:   'var(--radius-xl)',
        '2xl':'var(--radius-2xl)',
        pill: 'var(--radius-pill)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        glow: 'var(--shadow-glow)',
        'glow-accent':  '0 0 0 1px var(--accent-glow), 0 0 24px -4px var(--accent-glow)',
        'glow-success': '0 0 0 1px var(--success-soft), 0 0 24px -4px var(--success-soft)',
        'glow-warning': '0 0 0 1px var(--warning-soft), 0 0 24px -4px var(--warning-soft)',
        'glow-danger':  '0 0 0 1px var(--danger-soft), 0 0 24px -4px var(--danger-soft)',
      },
      fontSize: {
        '2xs': ['10px', '14px'],
        xs:    ['11px', '16px'],
        sm:    ['13px', '18px'],
        base:  ['14px', '20px'],
        lg:    ['16px', '22px'],
        xl:    ['18px', '24px'],
        '2xl': ['22px', '28px'],
        '3xl': ['28px', '34px'],
        '4xl': ['36px', '42px'],
        '5xl': ['48px', '54px'],
      },
      keyframes: {
        'slide-up':    { from: { opacity: 0, transform: 'translateY(8px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        'slide-down':  { from: { opacity: 0, transform: 'translateY(-8px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        'slide-right': { from: { opacity: 0, transform: 'translateX(-8px)' }, to: { opacity: 1, transform: 'translateX(0)' } },
        'slide-in':    { from: { opacity: 0, transform: 'translateX(8px)' }, to: { opacity: 1, transform: 'translateX(0)' } },
        'slide-out':   { from: { opacity: 1, transform: 'translateX(0)' }, to: { opacity: 0, transform: 'translateX(8px)' } },
        'fade-in':     { from: { opacity: 0 }, to: { opacity: 1 } },
        'fade-out':    { from: { opacity: 1 }, to: { opacity: 0 } },
        'scale-in':    { from: { opacity: 0, transform: 'scale(0.96)' }, to: { opacity: 1, transform: 'scale(1)' } },
        'scale-out':   { from: { opacity: 1, transform: 'scale(1)' }, to: { opacity: 0, transform: 'scale(0.96)' } },
        shimmer:       { '0%': { backgroundPosition: '200% 0' }, '100%': { backgroundPosition: '-200% 0' } },
        'pulse-ring':  { '0%': { transform: 'scale(0.6)', opacity: '0.7' }, '100%': { transform: 'scale(1.6)', opacity: '0' } },
        ticker:        { from: { transform: 'translateY(0)' }, to: { transform: 'translateY(-50%)' } },
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up':   { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        'caret-blink':    { '0%,50%,100%': { opacity: '1' }, '25%,75%': { opacity: '0' } },
      },
      animation: {
        'slide-up':    'slide-up 0.4s var(--ease) both',
        'slide-down':  'slide-down 0.3s var(--ease) both',
        'slide-right': 'slide-right 0.3s var(--ease) both',
        'slide-in':    'slide-in 0.3s var(--ease) both',
        'slide-out':   'slide-out 0.2s var(--ease) both',
        'fade-in':     'fade-in 0.3s var(--ease) both',
        'fade-out':    'fade-out 0.2s var(--ease) both',
        'scale-in':    'scale-in 0.3s var(--ease) both',
        'scale-out':   'scale-out 0.2s var(--ease) both',
        shimmer:       'shimmer 1.6s linear infinite',
        'pulse-ring':  'pulse-ring 2s var(--ease) infinite',
        ticker:        'ticker 30s linear infinite',
        'accordion-down': 'accordion-down 0.2s var(--ease)',
        'accordion-up':   'accordion-up 0.2s var(--ease)',
        'caret-blink':    'caret-blink 1.2s var(--ease) infinite',
      },
    },
  },
  plugins: [],
};
