/**
 * Comprehensive AI Provider Catalog
 *
 * 35+ providers with API details, modalities, and adapter configurations.
 * Users can add any of these via: dmrx add-provider <provider-id>
 */
/**
 * Full provider catalog
 */
export const PROVIDER_CATALOG = [
    // ═══════════════════════════════════════════════════════════
    // CLOUD LLM PROVIDERS
    // ═══════════════════════════════════════════════════════════
    {
        id: 'openai',
        name: 'OpenAI',
        category: 'cloud_llm',
        baseUrl: 'https://api.openai.com/v1',
        authMethod: 'bearer',
        apiFormat: 'openai',
        modalities: ['llm', 'embedding', 'audio_tts', 'audio_stt', 'diffusion'],
        models: [
            { id: 'gpt-4o', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 2.5, outputCostPer1M: 10, capabilities: ['vision', 'tool_use', 'json_mode', 'streaming'], specializations: ['backend_api', 'backend_logic', 'general'] },
            { id: 'gpt-4o-mini', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 0.15, outputCostPer1M: 0.6, capabilities: ['vision', 'tool_use', 'json_mode', 'streaming'], specializations: ['bulk_generation', 'fast', 'cheap'] },
            { id: 'gpt-4.1', modalities: ['llm'], contextWindow: 1000000, inputCostPer1M: 2, outputCostPer1M: 8, capabilities: ['vision', 'tool_use', 'json_mode', 'streaming'], specializations: ['backend_api', 'general'] },
            { id: 'gpt-4.1-mini', modalities: ['llm'], contextWindow: 1000000, inputCostPer1M: 0.4, outputCostPer1M: 1.6, capabilities: ['vision', 'tool_use', 'json_mode', 'streaming'], specializations: ['bulk_generation', 'fast'] },
            { id: 'o3', modalities: ['llm'], contextWindow: 200000, inputCostPer1M: 10, outputCostPer1M: 40, capabilities: ['reasoning', 'tool_use', 'streaming'], specializations: ['reasoning', 'architecture'] },
            { id: 'o3-mini', modalities: ['llm'], contextWindow: 200000, inputCostPer1M: 1.1, outputCostPer1M: 4.4, capabilities: ['reasoning', 'tool_use', 'streaming'], specializations: ['reasoning'] },
            { id: 'o4-mini', modalities: ['llm'], contextWindow: 200000, inputCostPer1M: 1.1, outputCostPer1M: 4.4, capabilities: ['reasoning', 'tool_use', 'streaming'], specializations: ['reasoning'] },
            { id: 'dall-e-3', modalities: ['diffusion'], costPerImage: 0.04, capabilities: ['text2img'], specializations: ['creative'] },
            { id: 'text-embedding-3-small', modalities: ['embedding'], inputCostPer1M: 0.02, capabilities: ['embedding'], specializations: ['embedding'] },
            { id: 'text-embedding-3-large', modalities: ['embedding'], inputCostPer1M: 0.13, capabilities: ['embedding'], specializations: ['embedding'] },
            { id: 'whisper-1', modalities: ['audio_stt'], capabilities: ['stt'], specializations: ['audio'] },
            { id: 'tts-1', modalities: ['audio_tts'], capabilities: ['tts'], specializations: ['audio'] },
        ],
        streaming: true,
        toolCalling: true,
        envKey: 'OPENAI_API_KEY',
        description: 'Industry standard. GPT-4o, o3, DALL-E, Whisper, embeddings.',
    },
    {
        id: 'anthropic',
        name: 'Anthropic',
        category: 'cloud_llm',
        baseUrl: 'https://api.anthropic.com/v1',
        authMethod: 'x-api-key',
        apiFormat: 'anthropic',
        modalities: ['llm'],
        models: [
            { id: 'claude-opus-4-0520', modalities: ['llm'], contextWindow: 200000, inputCostPer1M: 15, outputCostPer1M: 75, capabilities: ['vision', 'tool_use', 'streaming'], specializations: ['architecture', 'reasoning', 'code_review'] },
            { id: 'claude-sonnet-4-0520', modalities: ['llm'], contextWindow: 200000, inputCostPer1M: 3, outputCostPer1M: 15, capabilities: ['vision', 'tool_use', 'streaming'], specializations: ['ui_design', 'frontend_logic', 'creative'] },
            { id: 'claude-3.5-sonnet', modalities: ['llm'], contextWindow: 200000, inputCostPer1M: 3, outputCostPer1M: 15, capabilities: ['vision', 'tool_use', 'streaming'], specializations: ['ui_design', 'ui_component', 'code_review'] },
            { id: 'claude-3.5-haiku', modalities: ['llm'], contextWindow: 200000, inputCostPer1M: 0.8, outputCostPer1M: 4, capabilities: ['vision', 'tool_use', 'streaming'], specializations: ['fast', 'bulk_generation'] },
        ],
        streaming: true,
        toolCalling: true,
        envKey: 'ANTHROPIC_API_KEY',
        description: 'Claude models. Best for UI, frontend, creative, code review.',
    },
    {
        id: 'google',
        name: 'Google Gemini',
        category: 'cloud_llm',
        baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
        authMethod: 'api-key-param',
        apiFormat: 'google',
        modalities: ['llm', 'embedding', 'audio_stt', 'diffusion'],
        models: [
            { id: 'gemini-2.5-pro', modalities: ['llm'], contextWindow: 1000000, inputCostPer1M: 1.25, outputCostPer1M: 5, capabilities: ['vision', 'tool_use', 'streaming'], specializations: ['reasoning', 'general'] },
            { id: 'gemini-2.5-flash', modalities: ['llm'], contextWindow: 1000000, inputCostPer1M: 0.15, outputCostPer1M: 0.6, capabilities: ['vision', 'tool_use', 'streaming'], specializations: ['fast', 'cheap'] },
            { id: 'gemini-2.0-flash', modalities: ['llm'], contextWindow: 1000000, inputCostPer1M: 0.1, outputCostPer1M: 0.4, capabilities: ['vision', 'tool_use', 'streaming'], specializations: ['fast', 'cheap'] },
            { id: 'text-embedding-004', modalities: ['embedding'], capabilities: ['embedding'], specializations: ['embedding'] },
            { id: 'imagen-3.0', modalities: ['diffusion'], capabilities: ['text2img'], specializations: ['creative'] },
        ],
        streaming: true,
        toolCalling: true,
        envKey: 'GOOGLE_API_KEY',
        description: 'Gemini models. 1M+ context, fast, cheap.',
    },
    {
        id: 'mistral',
        name: 'Mistral AI',
        category: 'cloud_llm',
        baseUrl: 'https://api.mistral.ai/v1',
        authMethod: 'bearer',
        apiFormat: 'openai',
        modalities: ['llm', 'embedding'],
        models: [
            { id: 'mistral-large-latest', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 2, outputCostPer1M: 6, capabilities: ['tool_use', 'json_mode', 'streaming'], specializations: ['backend_api', 'general'] },
            { id: 'mistral-small-latest', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 0.1, outputCostPer1M: 0.3, capabilities: ['tool_use', 'json_mode', 'streaming'], specializations: ['fast', 'cheap'] },
            { id: 'codestral-latest', modalities: ['llm'], contextWindow: 256000, inputCostPer1M: 0.3, outputCostPer1M: 0.9, capabilities: ['streaming'], specializations: ['bulk_generation', 'backend_logic'] },
            { id: 'pixtral-large-latest', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 2, outputCostPer1M: 6, capabilities: ['vision', 'tool_use', 'streaming'], specializations: ['ui_design', 'general'] },
            { id: 'mistral-embed', modalities: ['embedding'], capabilities: ['embedding'], specializations: ['embedding'] },
        ],
        streaming: true,
        toolCalling: true,
        envKey: 'MISTRAL_API_KEY',
        description: 'Mistral models. OpenAI-compatible. Codestral for code.',
    },
    {
        id: 'deepseek',
        name: 'DeepSeek',
        category: 'cloud_llm',
        baseUrl: 'https://api.deepseek.com/v1',
        authMethod: 'bearer',
        apiFormat: 'openai',
        modalities: ['llm'],
        models: [
            { id: 'deepseek-chat', modalities: ['llm'], contextWindow: 64000, inputCostPer1M: 0.14, outputCostPer1M: 0.28, capabilities: ['tool_use', 'json_mode', 'streaming'], specializations: ['bulk_generation', 'cheap', 'documentation'] },
            { id: 'deepseek-reasoner', modalities: ['llm'], contextWindow: 64000, inputCostPer1M: 0.55, outputCostPer1M: 2.19, capabilities: ['reasoning', 'streaming'], specializations: ['reasoning'] },
        ],
        streaming: true,
        toolCalling: true,
        envKey: 'DEEPSEEK_API_KEY',
        description: 'DeepSeek models. Very cheap, good for bulk work.',
    },
    {
        id: 'xai',
        name: 'xAI (Grok)',
        category: 'cloud_llm',
        baseUrl: 'https://api.x.ai/v1',
        authMethod: 'bearer',
        apiFormat: 'openai',
        modalities: ['llm'],
        models: [
            { id: 'grok-3', modalities: ['llm'], contextWindow: 131072, inputCostPer1M: 3, outputCostPer1M: 15, capabilities: ['vision', 'tool_use', 'streaming'], specializations: ['general', 'creative'] },
            { id: 'grok-3-mini', modalities: ['llm'], contextWindow: 131072, inputCostPer1M: 0.3, outputCostPer1M: 0.5, capabilities: ['tool_use', 'streaming'], specializations: ['fast', 'cheap'] },
        ],
        streaming: true,
        toolCalling: true,
        envKey: 'XAI_API_KEY',
        description: 'Grok models from xAI.',
    },
    {
        id: 'moonshot',
        name: 'Moonshot (Kimi)',
        category: 'cloud_llm',
        baseUrl: 'https://api.moonshot.cn/v1',
        authMethod: 'bearer',
        apiFormat: 'openai',
        modalities: ['llm'],
        models: [
            { id: 'kimi-k2.6', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 1, outputCostPer1M: 3, capabilities: ['tool_use', 'streaming'], specializations: ['orchestration', 'architecture', 'reasoning'] },
            { id: 'moonshot-v1-128k', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 0.5, outputCostPer1M: 1.5, capabilities: ['streaming'], specializations: ['general'] },
        ],
        streaming: true,
        toolCalling: true,
        envKey: 'MOONSHOT_API_KEY',
        description: 'Kimi models. Good for orchestration and long context.',
    },
    {
        id: 'xiaomi',
        name: 'Xiaomi (MiMo)',
        category: 'cloud_llm',
        baseUrl: 'https://api.xiaomi.com/v1',
        authMethod: 'bearer',
        apiFormat: 'openai',
        modalities: ['llm'],
        models: [
            { id: 'mimo-v2', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 0.5, outputCostPer1M: 1.5, capabilities: ['tool_use', 'streaming'], specializations: ['database_schema', 'database_query', 'data_modeling', 'orm'] },
        ],
        streaming: true,
        toolCalling: true,
        envKey: 'XIAOMI_API_KEY',
        description: 'MiMo models. Strong at database and structured data.',
    },
    {
        id: 'cohere',
        name: 'Cohere',
        category: 'cloud_llm',
        baseUrl: 'https://api.cohere.com/v2',
        authMethod: 'bearer',
        apiFormat: 'custom',
        modalities: ['llm', 'embedding', 'reranking'],
        models: [
            { id: 'command-r-plus', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 2.5, outputCostPer1M: 10, capabilities: ['tool_use', 'streaming'], specializations: ['backend_api', 'general'] },
            { id: 'command-r', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 0.15, outputCostPer1M: 0.6, capabilities: ['tool_use', 'streaming'], specializations: ['fast', 'cheap'] },
            { id: 'embed-english-v3.0', modalities: ['embedding'], capabilities: ['embedding'], specializations: ['embedding'] },
            { id: 'embed-multilingual-v3.0', modalities: ['embedding'], capabilities: ['embedding'], specializations: ['embedding'] },
            { id: 'rerank-english-v3.0', modalities: ['reranking'], capabilities: ['reranking'], specializations: ['reranking'] },
            { id: 'rerank-multilingual-v3.0', modalities: ['reranking'], capabilities: ['reranking'], specializations: ['reranking'] },
        ],
        streaming: true,
        toolCalling: true,
        envKey: 'COHERE_API_KEY',
        description: 'Cohere models. Best for reranking and enterprise search.',
    },
    // ═══════════════════════════════════════════════════════════
    // HOSTING / AGGREGATION PLATFORMS
    // ═══════════════════════════════════════════════════════════
    {
        id: 'together',
        name: 'Together AI',
        category: 'hosting',
        baseUrl: 'https://api.together.xyz/v1',
        authMethod: 'bearer',
        apiFormat: 'openai',
        modalities: ['llm', 'embedding', 'diffusion'],
        models: [
            { id: 'meta-llama/Llama-4-Maverick-17B-128E-Instruct', modalities: ['llm'], inputCostPer1M: 0.2, outputCostPer1M: 0.2, capabilities: ['tool_use', 'streaming'], specializations: ['general'] },
            { id: 'meta-llama/Llama-3.3-70B-Instruct-Turbo', modalities: ['llm'], inputCostPer1M: 0.88, outputCostPer1M: 0.88, capabilities: ['tool_use', 'streaming'], specializations: ['general'] },
            { id: 'Qwen/Qwen2.5-72B-Instruct-Turbo', modalities: ['llm'], inputCostPer1M: 1.2, outputCostPer1M: 1.2, capabilities: ['tool_use', 'streaming'], specializations: ['general'] },
        ],
        streaming: true,
        toolCalling: true,
        envKey: 'TOGETHER_API_KEY',
        description: 'Open-source model hosting. Llama, Qwen, Mistral, and more.',
    },
    {
        id: 'fireworks',
        name: 'Fireworks AI',
        category: 'hosting',
        baseUrl: 'https://api.fireworks.ai/inference/v1',
        authMethod: 'bearer',
        apiFormat: 'openai',
        modalities: ['llm', 'embedding'],
        models: [
            { id: 'accounts/fireworks/models/llama-v3p3-70b-instruct', modalities: ['llm'], inputCostPer1M: 0.9, outputCostPer1M: 0.9, capabilities: ['tool_use', 'streaming'], specializations: ['general'] },
            { id: 'accounts/fireworks/models/deepseek-v3', modalities: ['llm'], inputCostPer1M: 0.9, outputCostPer1M: 0.9, capabilities: ['tool_use', 'streaming'], specializations: ['general'] },
        ],
        streaming: true,
        toolCalling: true,
        envKey: 'FIREWORKS_API_KEY',
        description: 'Fast inference for open-source models.',
    },
    {
        id: 'groq',
        name: 'Groq',
        category: 'hosting',
        baseUrl: 'https://api.groq.com/openai/v1',
        authMethod: 'bearer',
        apiFormat: 'openai',
        modalities: ['llm'],
        models: [
            { id: 'llama-3.3-70b-versatile', modalities: ['llm'], inputCostPer1M: 0.59, outputCostPer1M: 0.79, capabilities: ['tool_use', 'streaming'], specializations: ['fast', 'general'] },
            { id: 'llama-3.1-8b-instant', modalities: ['llm'], inputCostPer1M: 0.05, outputCostPer1M: 0.08, capabilities: ['streaming'], specializations: ['fast', 'cheap'] },
            { id: 'mixtral-8x7b-32768', modalities: ['llm'], inputCostPer1M: 0.24, outputCostPer1M: 0.24, capabilities: ['streaming'], specializations: ['fast', 'cheap'] },
        ],
        streaming: true,
        toolCalling: true,
        envKey: 'GROQ_API_KEY',
        description: 'Ultra-fast LPU inference. Fastest LLM hosting.',
    },
    {
        id: 'cerebras',
        name: 'Cerebras',
        category: 'hosting',
        baseUrl: 'https://api.cerebras.ai/v1',
        authMethod: 'bearer',
        apiFormat: 'openai',
        modalities: ['llm'],
        models: [
            { id: 'llama-3.3-70b', modalities: ['llm'], inputCostPer1M: 0.6, outputCostPer1M: 0.6, capabilities: ['streaming'], specializations: ['fast'] },
            { id: 'llama-3.1-8b', modalities: ['llm'], inputCostPer1M: 0.1, outputCostPer1M: 0.1, capabilities: ['streaming'], specializations: ['fast', 'cheap'] },
        ],
        streaming: true,
        toolCalling: false,
        envKey: 'CEREBRAS_API_KEY',
        description: 'Wafer-scale inference. Extremely fast.',
    },
    {
        id: 'sambanova',
        name: 'SambaNova',
        category: 'hosting',
        baseUrl: 'https://api.sambanova.ai/v1',
        authMethod: 'bearer',
        apiFormat: 'openai',
        modalities: ['llm'],
        models: [
            { id: 'Meta-Llama-3.3-70B-Instruct', modalities: ['llm'], inputCostPer1M: 0.6, outputCostPer1M: 0.6, capabilities: ['streaming'], specializations: ['fast'] },
        ],
        streaming: true,
        toolCalling: false,
        envKey: 'SAMBANOVA_API_KEY',
        description: 'RDU-based inference. Fast and cost-effective.',
    },
    {
        id: 'replicate',
        name: 'Replicate',
        category: 'hosting',
        baseUrl: 'https://api.replicate.com/v1',
        authMethod: 'bearer',
        apiFormat: 'custom',
        modalities: ['llm', 'diffusion', 'audio_tts', 'audio_stt', 'video'],
        models: [
            { id: 'stability-ai/sdxl', modalities: ['diffusion'], costPerImage: 0.0023, capabilities: ['text2img'], specializations: ['creative'] },
            { id: 'black-forest-labs/flux-schnell', modalities: ['diffusion'], costPerImage: 0.003, capabilities: ['text2img'], specializations: ['creative'] },
            { id: 'meta/musicgen', modalities: ['music'], capabilities: ['music_generation'], specializations: ['creative'] },
        ],
        streaming: false,
        toolCalling: false,
        envKey: 'REPLICATE_API_TOKEN',
        description: 'Run any open-source model. Diffusion, video, audio.',
    },
    {
        id: 'huggingface',
        name: 'Hugging Face',
        category: 'hosting',
        baseUrl: 'https://router.huggingface.co/v1',
        authMethod: 'bearer',
        apiFormat: 'openai',
        modalities: ['llm', 'embedding', 'diffusion', 'audio_stt', 'audio_tts'],
        models: [
            { id: 'meta-llama/Llama-3.3-70B-Instruct', modalities: ['llm'], capabilities: ['streaming'], specializations: ['general'] },
            { id: 'black-forest-labs/FLUX.1-schnell', modalities: ['diffusion'], capabilities: ['text2img'], specializations: ['creative'] },
            { id: 'openai/whisper-large-v3', modalities: ['audio_stt'], capabilities: ['stt'], specializations: ['audio'] },
        ],
        streaming: true,
        toolCalling: false,
        envKey: 'HF_TOKEN',
        description: 'HF Inference Providers. Access 20+ backends with one token.',
    },
    // ═══════════════════════════════════════════════════════════
    // CLOUD DIFFUSION PROVIDERS
    // ═══════════════════════════════════════════════════════════
    {
        id: 'stability',
        name: 'Stability AI',
        category: 'cloud_diffusion',
        baseUrl: 'https://api.stability.ai/v1',
        authMethod: 'bearer',
        apiFormat: 'custom',
        modalities: ['diffusion'],
        models: [
            { id: 'stable-diffusion-xl-1024-v1-0', modalities: ['diffusion'], costPerImage: 0.002, capabilities: ['text2img', 'img2img'], specializations: ['creative'] },
            { id: 'stable-diffusion-3-medium', modalities: ['diffusion'], costPerImage: 0.03, capabilities: ['text2img'], specializations: ['creative'] },
        ],
        streaming: false,
        toolCalling: false,
        envKey: 'STABILITY_API_KEY',
        description: 'Stable Diffusion models. Text-to-image, img2img.',
    },
    {
        id: 'leonardo',
        name: 'Leonardo AI',
        category: 'cloud_diffusion',
        baseUrl: 'https://cloud.leonardo.ai/api/rest/v1',
        authMethod: 'bearer',
        apiFormat: 'custom',
        modalities: ['diffusion'],
        models: [
            { id: 'leonardo-phoenix', modalities: ['diffusion'], capabilities: ['text2img', 'img2img'], specializations: ['creative'] },
            { id: 'leonardo-alchemy', modalities: ['diffusion'], capabilities: ['text2img'], specializations: ['creative'] },
        ],
        streaming: false,
        toolCalling: false,
        envKey: 'LEONARDO_API_KEY',
        description: 'AI image generation with fine-grained control.',
    },
    {
        id: 'ideogram',
        name: 'Ideogram',
        category: 'cloud_diffusion',
        baseUrl: 'https://api.ideogram.ai/v1',
        authMethod: 'bearer',
        apiFormat: 'custom',
        modalities: ['diffusion'],
        models: [
            { id: 'ideogram-2.0', modalities: ['diffusion'], capabilities: ['text2img'], specializations: ['creative'] },
        ],
        streaming: false,
        toolCalling: false,
        envKey: 'IDEOGRAM_API_KEY',
        description: 'Best at text-in-image generation.',
    },
    // ═══════════════════════════════════════════════════════════
    // CLOUD AUDIO PROVIDERS
    // ═══════════════════════════════════════════════════════════
    {
        id: 'elevenlabs',
        name: 'ElevenLabs',
        category: 'cloud_audio',
        baseUrl: 'https://api.elevenlabs.io/v1',
        authMethod: 'xi-api-key',
        apiFormat: 'custom',
        modalities: ['audio_tts'],
        models: [
            { id: 'eleven_multilingual_v2', modalities: ['audio_tts'], capabilities: ['tts', 'multilingual'], specializations: ['audio'] },
            { id: 'eleven_turbo_v2', modalities: ['audio_tts'], capabilities: ['tts'], specializations: ['audio', 'fast'] },
        ],
        streaming: true,
        toolCalling: false,
        envKey: 'ELEVENLABS_API_KEY',
        description: 'Highest quality TTS. Voice cloning.',
    },
    {
        id: 'deepgram',
        name: 'Deepgram',
        category: 'cloud_audio',
        baseUrl: 'https://api.deepgram.com/v1',
        authMethod: 'bearer',
        apiFormat: 'custom',
        modalities: ['audio_stt'],
        models: [
            { id: 'nova-2', modalities: ['audio_stt'], capabilities: ['stt', 'multilingual'], specializations: ['audio'] },
            { id: 'nova-3', modalities: ['audio_stt'], capabilities: ['stt', 'multilingual'], specializations: ['audio'] },
        ],
        streaming: true,
        toolCalling: false,
        envKey: 'DEEPGRAM_API_KEY',
        description: 'Fastest STT. Real-time transcription.',
    },
    {
        id: 'assemblyai',
        name: 'AssemblyAI',
        category: 'cloud_audio',
        baseUrl: 'https://api.assemblyai.com/v2',
        authMethod: 'bearer',
        apiFormat: 'custom',
        modalities: ['audio_stt'],
        models: [
            { id: 'best', modalities: ['audio_stt'], capabilities: ['stt'], specializations: ['audio'] },
            { id: 'nano', modalities: ['audio_stt'], capabilities: ['stt'], specializations: ['audio', 'fast'] },
        ],
        streaming: true,
        toolCalling: false,
        envKey: 'ASSEMBLYAI_API_KEY',
        description: 'Accurate STT with speaker diarization.',
    },
    {
        id: 'playht',
        name: 'PlayHT',
        category: 'cloud_audio',
        baseUrl: 'https://api.play.ht/api/v2',
        authMethod: 'bearer',
        apiFormat: 'custom',
        modalities: ['audio_tts'],
        models: [
            { id: 'PlayHT2.0', modalities: ['audio_tts'], capabilities: ['tts'], specializations: ['audio'] },
        ],
        streaming: true,
        toolCalling: false,
        envKey: 'PLAYHT_API_KEY',
        description: 'TTS with voice cloning.',
    },
    // ═══════════════════════════════════════════════════════════
    // CLOUD VIDEO PROVIDERS
    // ═══════════════════════════════════════════════════════════
    {
        id: 'runway',
        name: 'RunwayML',
        category: 'cloud_video',
        baseUrl: 'https://api.runwayml.com/v1',
        authMethod: 'bearer',
        apiFormat: 'custom',
        modalities: ['video'],
        models: [
            { id: 'gen-3-alpha', modalities: ['video'], capabilities: ['text2video', 'img2video'], specializations: ['creative'] },
        ],
        streaming: false,
        toolCalling: false,
        envKey: 'RUNWAY_API_KEY',
        description: 'AI video generation.',
    },
    {
        id: 'pika',
        name: 'Pika Labs',
        category: 'cloud_video',
        baseUrl: 'https://api.pika.art/v1',
        authMethod: 'bearer',
        apiFormat: 'custom',
        modalities: ['video'],
        models: [
            { id: 'pika-2.0', modalities: ['video'], capabilities: ['text2video', 'img2video'], specializations: ['creative'] },
        ],
        streaming: false,
        toolCalling: false,
        envKey: 'PIKA_API_KEY',
        description: 'AI video generation and editing.',
    },
    // ═══════════════════════════════════════════════════════════
    // EMBEDDING SPECIALISTS
    // ═══════════════════════════════════════════════════════════
    {
        id: 'jina',
        name: 'Jina AI',
        category: 'cloud_embedding',
        baseUrl: 'https://api.jina.ai/v1',
        authMethod: 'bearer',
        apiFormat: 'openai',
        modalities: ['embedding', 'reranking'],
        models: [
            { id: 'jina-embeddings-v3', modalities: ['embedding'], capabilities: ['embedding', 'multilingual'], specializations: ['embedding'] },
            { id: 'jina-reranker-v2-base-multilingual', modalities: ['reranking'], capabilities: ['reranking', 'multilingual'], specializations: ['reranking'] },
        ],
        streaming: true,
        toolCalling: false,
        envKey: 'JINA_API_KEY',
        description: 'Embeddings and reranking. Multilingual.',
    },
    {
        id: 'voyage',
        name: 'Voyage AI',
        category: 'cloud_embedding',
        baseUrl: 'https://api.voyageai.com/v1',
        authMethod: 'bearer',
        apiFormat: 'openai',
        modalities: ['embedding', 'reranking'],
        models: [
            { id: 'voyage-3', modalities: ['embedding'], capabilities: ['embedding'], specializations: ['embedding'] },
            { id: 'voyage-3-lite', modalities: ['embedding'], capabilities: ['embedding'], specializations: ['embedding', 'cheap'] },
            { id: 'rerank-2', modalities: ['reranking'], capabilities: ['reranking'], specializations: ['reranking'] },
        ],
        streaming: true,
        toolCalling: false,
        envKey: 'VOYAGE_API_KEY',
        description: 'Best-in-class embeddings and reranking.',
    },
    // ═══════════════════════════════════════════════════════════
    // LOCAL MODEL PLATFORMS
    // ═══════════════════════════════════════════════════════════
    {
        id: 'ollama',
        name: 'Ollama (Local)',
        category: 'local',
        baseUrl: 'http://localhost:11434/v1',
        authMethod: 'bearer',
        apiFormat: 'openai',
        modalities: ['llm', 'embedding'],
        models: [], // Auto-discovered
        streaming: true,
        toolCalling: true,
        envKey: 'OLLAMA_BASE_URL',
        description: 'Local model runner. Pull-and-run. CPU/GPU.',
    },
    {
        id: 'vllm',
        name: 'vLLM (Local)',
        category: 'local',
        baseUrl: 'http://localhost:8000/v1',
        authMethod: 'bearer',
        apiFormat: 'openai',
        modalities: ['llm'],
        models: [], // Configured at serve time
        streaming: true,
        toolCalling: true,
        envKey: 'VLLM_BASE_URL',
        description: 'High-throughput local inference. PagedAttention.',
    },
    {
        id: 'llamacpp',
        name: 'llama.cpp (Local)',
        category: 'local',
        baseUrl: 'http://localhost:8080/v1',
        authMethod: 'bearer',
        apiFormat: 'openai',
        modalities: ['llm'],
        models: [], // Loaded at startup
        streaming: true,
        toolCalling: false,
        envKey: 'LLAMACPP_BASE_URL',
        description: 'C/C++ inference. CPU, GPU, Metal, Vulkan.',
    },
    {
        id: 'localai',
        name: 'LocalAI',
        category: 'local',
        baseUrl: 'http://localhost:8080/v1',
        authMethod: 'bearer',
        apiFormat: 'openai',
        modalities: ['llm', 'embedding', 'diffusion', 'audio_stt'],
        models: [], // Auto-downloaded from HF
        streaming: true,
        toolCalling: false,
        envKey: 'LOCALAI_BASE_URL',
        description: 'Unified local API. OpenAI-compatible. Multi-model.',
    },
    // ═══════════════════════════════════════════════════════════
    // FREE-TIER PROVIDERS (via GenericOpenAIAdapter)
    // ═══════════════════════════════════════════════════════════
    {
        id: 'nvidia-nim',
        name: 'NVIDIA NIM',
        category: 'hosting',
        baseUrl: 'https://integrate.api.nvidia.com/v1',
        authMethod: 'bearer',
        apiFormat: 'openai',
        modalities: ['llm'],
        models: [
            { id: 'meta/llama-3.1-8b-instruct', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['streaming'], specializations: ['fast', 'cheap'], freeTier: { rateLimits: { rpm: 3, rpd: 1000, tpm: 4000, tpd: 500000 }, monthlyTokenBudget: 500000, intelligenceRank: 7, speedRank: 9 } },
            { id: 'meta/llama-3.3-70b-instruct', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['tool_use', 'streaming'], specializations: ['general'], freeTier: { rateLimits: { rpm: 3, rpd: 1000, tpm: 4000, tpd: 500000 }, monthlyTokenBudget: 500000, intelligenceRank: 8, speedRank: 8 } },
            { id: 'meta/llama-4-maverick-17b-128e-instruct', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['tool_use', 'streaming'], specializations: ['general'], freeTier: { rateLimits: { rpm: 3, rpd: 1000, tpm: 4000, tpd: 500000 }, monthlyTokenBudget: 500000, intelligenceRank: 8, speedRank: 8 } },
            { id: 'deepseek-ai/deepseek-r1', modalities: ['llm'], contextWindow: 64000, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['reasoning', 'streaming'], specializations: ['reasoning'], freeTier: { rateLimits: { rpm: 3, rpd: 1000, tpm: 4000, tpd: 500000 }, monthlyTokenBudget: 500000, intelligenceRank: 9, speedRank: 6 } },
            { id: 'mistralai/mistral-large-3-675b-instruct', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['tool_use', 'streaming'], specializations: ['general'], freeTier: { rateLimits: { rpm: 3, rpd: 1000, tpm: 4000, tpd: 500000 }, monthlyTokenBudget: 500000, intelligenceRank: 9, speedRank: 7 } },
        ],
        streaming: true,
        toolCalling: true,
        envKey: 'NVIDIA_NIM_API_KEY',
        description: 'NVIDIA NIM free tier. Llama, DeepSeek, Mistral on NVIDIA GPUs.',
    },
    {
        id: 'github-models',
        name: 'GitHub Models',
        category: 'hosting',
        baseUrl: 'https://models.inference.ai.azure.com',
        authMethod: 'bearer',
        apiFormat: 'openai',
        modalities: ['llm', 'embedding'],
        models: [
            { id: 'gpt-4o-mini', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['vision', 'tool_use', 'streaming'], specializations: ['fast', 'cheap'], freeTier: { rateLimits: { rpm: 15, rpd: 150, tpm: 8000, tpd: 0 }, monthlyTokenBudget: 800000, intelligenceRank: 8, speedRank: 8 } },
            { id: 'gpt-4o', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['vision', 'tool_use', 'streaming'], specializations: ['general'], freeTier: { rateLimits: { rpm: 15, rpd: 150, tpm: 8000, tpd: 0 }, monthlyTokenBudget: 800000, intelligenceRank: 9, speedRank: 8 } },
            { id: 'gpt-4.1', modalities: ['llm'], contextWindow: 1000000, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['vision', 'tool_use', 'streaming'], specializations: ['general'], freeTier: { rateLimits: { rpm: 15, rpd: 150, tpm: 8000, tpd: 0 }, monthlyTokenBudget: 800000, intelligenceRank: 9, speedRank: 8 } },
            { id: 'text-embedding-3-small', modalities: ['embedding'], inputCostPer1M: 0, capabilities: ['embedding'], specializations: ['embedding'], freeTier: { rateLimits: { rpm: 15, rpd: 150, tpm: 0, tpd: 0 }, monthlyTokenBudget: 0, intelligenceRank: 0, speedRank: 8 } },
        ],
        streaming: true,
        toolCalling: true,
        envKey: 'GITHUB_TOKEN',
        description: 'GitHub Models free tier. GPT-4o, GPT-4.1 with GitHub PAT.',
    },
    {
        id: 'cloudflare-ai',
        name: 'Cloudflare Workers AI',
        category: 'hosting',
        baseUrl: 'https://api.cloudflare.com/client/v4/accounts/{ACCOUNT_ID}/ai/v1',
        authMethod: 'bearer',
        apiFormat: 'openai',
        modalities: ['llm'],
        models: [
            { id: '@cf/meta/llama-3.3-70b-instruct-fp8', modalities: ['llm'], contextWindow: 8192, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['streaming'], specializations: ['general'], freeTier: { rateLimits: { rpm: 300, rpd: 0, tpm: 0, tpd: 0 }, monthlyTokenBudget: 10000000, intelligenceRank: 7, speedRank: 9 } },
            { id: '@cf/meta/llama-4-scout-17b-16e-instruct', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['streaming'], specializations: ['general'], freeTier: { rateLimits: { rpm: 300, rpd: 0, tpm: 0, tpd: 0 }, monthlyTokenBudget: 10000000, intelligenceRank: 8, speedRank: 8 } },
            { id: '@cf/deepseek-ai/deepseek-r1-distill-qwen-32b', modalities: ['llm'], contextWindow: 32768, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['reasoning', 'streaming'], specializations: ['reasoning'], freeTier: { rateLimits: { rpm: 300, rpd: 0, tpm: 0, tpd: 0 }, monthlyTokenBudget: 10000000, intelligenceRank: 8, speedRank: 7 } },
            { id: '@cf/qwen/qwen3-30b-a3b', modalities: ['llm'], contextWindow: 32768, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['streaming'], specializations: ['general'], freeTier: { rateLimits: { rpm: 300, rpd: 0, tpm: 0, tpd: 0 }, monthlyTokenBudget: 10000000, intelligenceRank: 7, speedRank: 8 } },
            { id: '@cf/ibm-granite/granite-4.0-micro', modalities: ['llm'], contextWindow: 8192, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['streaming'], specializations: ['fast', 'cheap'], freeTier: { rateLimits: { rpm: 300, rpd: 0, tpm: 0, tpd: 0 }, monthlyTokenBudget: 10000000, intelligenceRank: 5, speedRank: 10 } },
        ],
        streaming: true,
        toolCalling: false,
        envKey: 'CLOUDFLARE_AI_TOKEN',
        description: 'Cloudflare Workers AI free tier. Replace {ACCOUNT_ID} in URL.',
    },
    {
        id: 'zhipu',
        name: 'Zhipu (Z.ai)',
        category: 'cloud_llm',
        baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
        authMethod: 'bearer',
        apiFormat: 'openai',
        modalities: ['llm'],
        models: [
            { id: 'glm-4.5-flash', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['streaming'], specializations: ['fast', 'cheap'], freeTier: { rateLimits: { rpm: 10, rpd: 0, tpm: 0, tpd: 0 }, monthlyTokenBudget: 5000000, intelligenceRank: 7, speedRank: 9 } },
            { id: 'glm-4.7-flash', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['streaming'], specializations: ['fast', 'cheap'], freeTier: { rateLimits: { rpm: 10, rpd: 0, tpm: 0, tpd: 0 }, monthlyTokenBudget: 5000000, intelligenceRank: 7, speedRank: 9 } },
        ],
        streaming: true,
        toolCalling: false,
        envKey: 'ZHIPU_API_KEY',
        description: 'Zhipu GLM models. Chinese LLM with free tier.',
    },
    {
        id: 'openrouter-free',
        name: 'OpenRouter (Free)',
        category: 'hosting',
        baseUrl: 'https://openrouter.ai/api/v1',
        authMethod: 'bearer',
        apiFormat: 'openai',
        modalities: ['llm'],
        models: [
            { id: 'qwen/qwen3-coder', modalities: ['llm'], contextWindow: 256000, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['tool_use', 'streaming'], specializations: ['bulk_generation', 'backend_logic'], freeTier: { rateLimits: { rpm: 20, rpd: 0, tpm: 0, tpd: 0 }, monthlyTokenBudget: 1000000, intelligenceRank: 8, speedRank: 7 } },
            { id: 'minimax/minimax-m2.5', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['streaming'], specializations: ['general'], freeTier: { rateLimits: { rpm: 20, rpd: 0, tpm: 0, tpd: 0 }, monthlyTokenBudget: 1000000, intelligenceRank: 7, speedRank: 8 } },
            { id: 'nvidia/llama-3.1-nemotron-ultra-253b-v1', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['streaming'], specializations: ['general'], freeTier: { rateLimits: { rpm: 20, rpd: 0, tpm: 0, tpd: 0 }, monthlyTokenBudget: 1000000, intelligenceRank: 8, speedRank: 7 } },
            { id: 'thudm/glm-4.7', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['streaming'], specializations: ['general'], freeTier: { rateLimits: { rpm: 20, rpd: 0, tpm: 0, tpd: 0 }, monthlyTokenBudget: 1000000, intelligenceRank: 7, speedRank: 8 } },
            { id: 'openai/gpt-oss-20b', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['streaming'], specializations: ['fast', 'cheap'], freeTier: { rateLimits: { rpm: 20, rpd: 0, tpm: 0, tpd: 0 }, monthlyTokenBudget: 1000000, intelligenceRank: 6, speedRank: 9 } },
        ],
        streaming: true,
        toolCalling: true,
        envKey: 'OPENROUTER_API_KEY',
        description: 'OpenRouter free models. ~19 free-tier models available.',
    },
    {
        id: 'pollinations',
        name: 'Pollinations',
        category: 'hosting',
        baseUrl: 'https://text.pollinations.ai/openai',
        authMethod: 'bearer',
        apiFormat: 'openai',
        modalities: ['llm'],
        models: [
            { id: 'openai/gpt-oss-20b', modalities: ['llm'], contextWindow: 32768, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['streaming'], specializations: ['fast', 'cheap'], freeTier: { rateLimits: { rpm: 10, rpd: 0, tpm: 0, tpd: 0 }, monthlyTokenBudget: 500000, intelligenceRank: 6, speedRank: 9 } },
        ],
        streaming: true,
        toolCalling: false,
        envKey: '', // No API key needed
        description: 'Pollinations free tier. Anonymous access, no key required.',
    },
    {
        id: 'llm7',
        name: 'LLM7',
        category: 'hosting',
        baseUrl: 'https://api.llm7.io/v1',
        authMethod: 'bearer',
        apiFormat: 'openai',
        modalities: ['llm'],
        models: [
            { id: 'openai/gpt-oss-20b', modalities: ['llm'], contextWindow: 32768, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['streaming'], specializations: ['fast', 'cheap'], freeTier: { rateLimits: { rpm: 10, rpd: 0, tpm: 0, tpd: 0 }, monthlyTokenBudget: 500000, intelligenceRank: 6, speedRank: 9 } },
            { id: 'meta-llama/Llama-3.1-8B-Turbo', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['streaming'], specializations: ['fast', 'cheap'], freeTier: { rateLimits: { rpm: 10, rpd: 0, tpm: 0, tpd: 0 }, monthlyTokenBudget: 500000, intelligenceRank: 6, speedRank: 9 } },
            { id: 'mistralai/Codestral-2501', modalities: ['llm'], contextWindow: 256000, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['streaming'], specializations: ['bulk_generation', 'backend_logic'], freeTier: { rateLimits: { rpm: 10, rpd: 0, tpm: 0, tpd: 0 }, monthlyTokenBudget: 500000, intelligenceRank: 8, speedRank: 7 } },
            { id: 'THUDM/glm-4.6V-flash', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['vision', 'streaming'], specializations: ['fast', 'cheap'], freeTier: { rateLimits: { rpm: 10, rpd: 0, tpm: 0, tpd: 0 }, monthlyTokenBudget: 500000, intelligenceRank: 7, speedRank: 9 } },
        ],
        streaming: true,
        toolCalling: false,
        envKey: 'LLM7_API_KEY',
        description: 'LLM7 free API. Multiple open-source models.',
    },
    {
        id: 'kilo-gateway',
        name: 'Kilo Gateway',
        category: 'hosting',
        baseUrl: 'https://api.kilo.ai/v1',
        authMethod: 'bearer',
        apiFormat: 'openai',
        modalities: ['llm'],
        models: [
            { id: 'nvidia/llama-3.1-nemotron-super-120b-v1', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['streaming'], specializations: ['general'], freeTier: { rateLimits: { rpm: 10, rpd: 0, tpm: 0, tpd: 0 }, monthlyTokenBudget: 500000, intelligenceRank: 8, speedRank: 7 } },
        ],
        streaming: true,
        toolCalling: false,
        envKey: 'KILO_API_KEY',
        description: 'Kilo Gateway free tier. Nemotron 120B.',
    },
    {
        id: 'ollama-cloud',
        name: 'Ollama Cloud',
        category: 'hosting',
        baseUrl: 'https://api.ollama.com/v1',
        authMethod: 'bearer',
        apiFormat: 'openai',
        modalities: ['llm'],
        models: [
            { id: 'qwen3-coder:480b', modalities: ['llm'], contextWindow: 256000, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['tool_use', 'streaming'], specializations: ['bulk_generation', 'backend_logic'], freeTier: { rateLimits: { rpm: 10, rpd: 0, tpm: 0, tpd: 0 }, monthlyTokenBudget: 500000, intelligenceRank: 9, speedRank: 6 } },
            { id: 'mistral-large3:675b', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['tool_use', 'streaming'], specializations: ['general'], freeTier: { rateLimits: { rpm: 10, rpd: 0, tpm: 0, tpd: 0 }, monthlyTokenBudget: 500000, intelligenceRank: 9, speedRank: 6 } },
            { id: 'deepseek-v3.2', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['tool_use', 'streaming'], specializations: ['general'], freeTier: { rateLimits: { rpm: 10, rpd: 0, tpm: 0, tpd: 0 }, monthlyTokenBudget: 500000, intelligenceRank: 9, speedRank: 7 } },
            { id: 'kimi-k2-thinking', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['reasoning', 'streaming'], specializations: ['reasoning'], freeTier: { rateLimits: { rpm: 10, rpd: 0, tpm: 0, tpd: 0 }, monthlyTokenBudget: 500000, intelligenceRank: 9, speedRank: 7 } },
            { id: 'glm-4.7', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['streaming'], specializations: ['general'], freeTier: { rateLimits: { rpm: 10, rpd: 0, tpm: 0, tpd: 0 }, monthlyTokenBudget: 500000, intelligenceRank: 7, speedRank: 8 } },
            { id: 'openai/gpt-oss-120b', modalities: ['llm'], contextWindow: 128000, inputCostPer1M: 0, outputCostPer1M: 0, capabilities: ['streaming'], specializations: ['general'], freeTier: { rateLimits: { rpm: 10, rpd: 0, tpm: 0, tpd: 0 }, monthlyTokenBudget: 500000, intelligenceRank: 8, speedRank: 7 } },
        ],
        streaming: true,
        toolCalling: true,
        envKey: 'OLLAMA_CLOUD_API_KEY',
        description: 'Ollama Cloud free tier. Large open-source models.',
    },
];
/**
 * Get provider template by ID
 */
export function getProviderTemplate(id) {
    return PROVIDER_CATALOG.find((p) => p.id === id);
}
/**
 * Get all providers in a category
 */
export function getProvidersByCategory(category) {
    return PROVIDER_CATALOG.filter((p) => p.category === category);
}
/**
 * Get providers that support a specific modality
 */
export function getProvidersByModality(modality) {
    return PROVIDER_CATALOG.filter((p) => p.modalities.includes(modality));
}
/**
 * Search providers by name or description
 */
export function searchProviders(query) {
    const lower = query.toLowerCase();
    return PROVIDER_CATALOG.filter((p) => p.name.toLowerCase().includes(lower) ||
        p.description.toLowerCase().includes(lower) ||
        p.id.includes(lower));
}
//# sourceMappingURL=provider-catalog.js.map