/**
 * Type guards for OpenAI Responses API stream events and output items.
 * Ported from OpenRouter SDK's stream-type-guards.ts with adaptations for DMR-X.
 *
 * These type guards discriminate the union types that appear in SSE stream events
 * from the Responses API, enabling type-safe narrowing in stream transformers.
 */

// ---------------------------------------------------------------------------
// Annotation types
// ---------------------------------------------------------------------------

/** A citation to a file uploaded to the API. */
export interface FileCitationAnnotation {
  type: 'file_citation';
  index: number;
  filename: string;
  fileId: string;
}

/** A citation to a URL found in web search results. */
export interface URLCitationAnnotation {
  type: 'url_citation';
  title: string;
  url: string;
}

/** A reference to a file generated by the model. */
export interface FilePathAnnotation {
  type: 'file_path';
  index: number;
  fileId: string;
}

/** Union of all annotation types supported by the Responses API. */
export type OpenAIResponsesAnnotation =
  | FileCitationAnnotation
  | URLCitationAnnotation
  | FilePathAnnotation;

// ---------------------------------------------------------------------------
// Output content parts
// ---------------------------------------------------------------------------

/** A text content part in an output message. */
export interface OutputTextPart {
  type: 'output_text';
  text: string;
  annotations?: OpenAIResponsesAnnotation[];
}

/** A refusal content part in an output message. */
export interface RefusalPart {
  type: 'refusal';
  refusal: string;
}

/** Union of all content parts that can appear in an OutputMessage. */
export type OutputContentPart = OutputTextPart | RefusalPart;

// ---------------------------------------------------------------------------
// Output item types
// ---------------------------------------------------------------------------

/** An assistant message in the response output. */
export interface OutputMessage {
  id: string;
  type: 'message';
  role: 'assistant';
  status: 'in_progress' | 'completed';
  content: OutputContentPart[];
}

/** A function (tool) call item in the response output. */
export interface OutputFunctionCallItem {
  type: 'function_call';
  id: string;
  callId: string;
  name: string;
  arguments: string;
  status?: string;
}

/** A reasoning (thinking) item in the response output. */
export interface OutputReasoningItem {
  type: 'reasoning';
  id: string;
  status?: string;
  summary?: Array<{ type: 'summary_text'; text: string }>;
  encryptedContent?: string;
}

/** A web search call item in the response output. */
export interface OutputWebSearchCallItem {
  type: 'web_search_call';
  id: string;
  status: string;
}

/** A file search call item in the response output. */
export interface OutputFileSearchCallItem {
  type: 'file_search_call';
  id: string;
  queries: string[];
  status: string;
}

/** An image generation call item in the response output. */
export interface OutputImageGenerationCallItem {
  type: 'image_generation_call';
  id: string;
  result?: string;
  status: string;
}

/** A function call output item (tool result sent back to the model). */
export interface FunctionCallOutputItem {
  type: 'function_call_output';
  id?: string;
  callId: string;
  output: string;
}

/** Union of all output item types from a Responses API response. */
export type OutputItem =
  | OutputMessage
  | OutputFunctionCallItem
  | OutputReasoningItem
  | OutputWebSearchCallItem
  | OutputFileSearchCallItem
  | OutputImageGenerationCallItem
  | FunctionCallOutputItem;

// ---------------------------------------------------------------------------
// Responses result type
// ---------------------------------------------------------------------------

/** Top-level result from the OpenAI Responses API. */
export interface OpenResponsesResult {
  id: string;
  model?: string;
  status: 'completed' | 'failed' | 'incomplete';
  output: OutputItem[];
  /** Pre-concatenated text output, if available. */
  outputText?: string;
  usage?: {
    inputTokens?: number;
    outputTokens?: number;
    inputTokensDetails?: { cachedTokens?: number };
  };
  incompleteDetails?: {
    reason?: string;
  };
  error?: unknown;
}

// ---------------------------------------------------------------------------
// Chat assistant message type (chat completions format)
// ---------------------------------------------------------------------------

/** An assistant message in the chat completions format. */
export interface ChatAssistantMessage {
  role: 'assistant';
  content: string | null;
}

// ---------------------------------------------------------------------------
// Stream event types
// ---------------------------------------------------------------------------

/** Event: text delta emitted while streaming an output message. */
export interface OutputTextDeltaEvent {
  type: 'response.output_text.delta';
  itemId: string;
  delta: string;
}

/** Event: reasoning text delta emitted while streaming a reasoning item. */
export interface ReasoningDeltaEvent {
  type: 'response.reasoning_text.delta';
  itemId: string;
  delta: string;
}

/** Event: function call arguments delta. */
export interface FunctionCallArgumentsDeltaEvent {
  type: 'response.function_call_arguments.delta';
  itemId: string;
  delta: string;
}

/** Event: function call arguments fully received. */
export interface FunctionCallArgumentsDoneEvent {
  type: 'response.function_call_arguments.done';
  itemId: string;
  name: string;
  arguments: string;
}

/** Event: a new output item has been added to the response. */
export interface OutputItemAddedEvent {
  type: 'response.output_item.added';
  item: OutputItem;
}

/** Event: an output item has been finalized. */
export interface OutputItemDoneEvent {
  type: 'response.output_item.done';
  item: OutputItem;
}

/** Event: the response has completed successfully. */
export interface ResponseCompletedEvent {
  type: 'response.completed';
  response: OpenResponsesResult;
}

/** Event: the response has failed. */
export interface ResponseFailedEvent {
  type: 'response.failed';
  response: OpenResponsesResult;
}

/** Event: the response is incomplete (e.g. max tokens hit). */
export interface ResponseIncompleteEvent {
  type: 'response.incomplete';
  response: OpenResponsesResult;
}

/** Union of all recognized Responses API stream events. */
export type StreamEvents =
  | OutputTextDeltaEvent
  | ReasoningDeltaEvent
  | FunctionCallArgumentsDeltaEvent
  | FunctionCallArgumentsDoneEvent
  | OutputItemAddedEvent
  | OutputItemDoneEvent
  | ResponseCompletedEvent
  | ResponseFailedEvent
  | ResponseIncompleteEvent;

// ---------------------------------------------------------------------------
// Type guard helpers
// ---------------------------------------------------------------------------

function hasType(value: unknown): value is { type: string } {
  return typeof value === 'object' && value !== null && 'type' in value;
}

// ---------------------------------------------------------------------------
// Event type guards
// ---------------------------------------------------------------------------

export function isOutputTextDeltaEvent(event: unknown): event is OutputTextDeltaEvent {
  return hasType(event) && event.type === 'response.output_text.delta';
}

export function isReasoningDeltaEvent(event: unknown): event is ReasoningDeltaEvent {
  return hasType(event) && event.type === 'response.reasoning_text.delta';
}

export function isFunctionCallArgumentsDeltaEvent(
  event: unknown,
): event is FunctionCallArgumentsDeltaEvent {
  return hasType(event) && event.type === 'response.function_call_arguments.delta';
}

export function isFunctionCallArgumentsDoneEvent(
  event: unknown,
): event is FunctionCallArgumentsDoneEvent {
  return hasType(event) && event.type === 'response.function_call_arguments.done';
}

export function isOutputItemAddedEvent(event: unknown): event is OutputItemAddedEvent {
  return hasType(event) && event.type === 'response.output_item.added';
}

export function isOutputItemDoneEvent(event: unknown): event is OutputItemDoneEvent {
  return hasType(event) && event.type === 'response.output_item.done';
}

export function isResponseCompletedEvent(event: unknown): event is ResponseCompletedEvent {
  return hasType(event) && event.type === 'response.completed';
}

export function isResponseFailedEvent(event: unknown): event is ResponseFailedEvent {
  return hasType(event) && event.type === 'response.failed';
}

export function isResponseIncompleteEvent(event: unknown): event is ResponseIncompleteEvent {
  return hasType(event) && event.type === 'response.incomplete';
}

// ---------------------------------------------------------------------------
// Output item type guards
// ---------------------------------------------------------------------------

export function isOutputMessage(item: unknown): item is OutputMessage {
  return hasType(item) && item.type === 'message';
}

export function isFunctionCallItem(item: unknown): item is OutputFunctionCallItem {
  return hasType(item) && item.type === 'function_call';
}

export function isReasoningOutputItem(item: unknown): item is OutputReasoningItem {
  return hasType(item) && item.type === 'reasoning';
}

export function isWebSearchCallOutputItem(item: unknown): item is OutputWebSearchCallItem {
  return hasType(item) && item.type === 'web_search_call';
}

export function isFileSearchCallOutputItem(item: unknown): item is OutputFileSearchCallItem {
  return hasType(item) && item.type === 'file_search_call';
}

export function isImageGenerationCallOutputItem(
  item: unknown,
): item is OutputImageGenerationCallItem {
  return hasType(item) && item.type === 'image_generation_call';
}

// ---------------------------------------------------------------------------
// Content part type guards
// ---------------------------------------------------------------------------

export function isOutputTextPart(part: unknown): part is OutputTextPart {
  return hasType(part) && part.type === 'output_text';
}

export function isRefusalPart(part: unknown): part is RefusalPart {
  return hasType(part) && part.type === 'refusal';
}

// ---------------------------------------------------------------------------
// Annotation type guards
// ---------------------------------------------------------------------------

export function isFileCitationAnnotation(
  annotation: unknown,
): annotation is FileCitationAnnotation {
  return hasType(annotation) && annotation.type === 'file_citation';
}

export function isURLCitationAnnotation(
  annotation: unknown,
): annotation is URLCitationAnnotation {
  return hasType(annotation) && annotation.type === 'url_citation';
}

export function isFilePathAnnotation(annotation: unknown): annotation is FilePathAnnotation {
  return hasType(annotation) && annotation.type === 'file_path';
}
