/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Generated by `bun run mcp:catalog:gen` (scripts/generate-mcp-catalog.ts)
 * from:
 *   - packages/core/src/mcp-catalog.manifest.ts  (curated metadata)
 *   - vendored/servers                           (fork of modelcontextprotocol/servers)
 *
 * To add or change a server, edit the manifest and regenerate. Run
 * `bun run mcp:catalog:check` in CI to fail on drift.
 */

export type McpCatalogCategory =
  | 'development'
  | 'data'
  | 'productivity'
  | 'search'
  | 'cloud'
  | 'automation'
  | 'memory';

export interface McpCatalogEnvVar {
  /** Environment variable name, also the `{{token}}` used in `args`. */
  key: string;
  /** Human label for the generated form field. */
  label: string;
  /** Rendered under the field. Say where to obtain the value. */
  help?: string;
  /** Render as a password field and never echo the value back to the client. */
  secret?: boolean;
  /** A field may be optional — the server still starts without it. */
  optional?: boolean;
  /** Prefilled default for non-secret fields. */
  placeholder?: string;
}

export interface McpCatalogEntry {
  id: string;
  name: string;
  description: string;
  category: McpCatalogCategory;
  /** lucide-react icon name, resolved by the UI. */
  icon: string;
  transport: 'stdio' | 'sse' | 'http';
  command?: string;
  args?: string[];
  url?: string;
  requiredEnv: McpCatalogEnvVar[];
  docsUrl?: string;
  /** Official reference implementation vs. third-party. Shown as a badge. */
  official?: boolean;
}

export const MCP_CATALOG: readonly McpCatalogEntry[] = [
  {
    id: "filesystem",
    name: "Filesystem",
    category: "development",
    icon: "FolderOpen",
    transport: "stdio",
    requiredEnv: [
      { key: "ALLOWED_DIR", label: "Allowed directory", help: "Absolute path. The server can only reach files beneath it.", placeholder: "/Users/me/projects" },
    ],
    description: "MCP server for filesystem access",
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-filesystem", "{{ALLOWED_DIR}}"],
    official: true,
  },
  {
    id: "git",
    name: "Git",
    category: "development",
    icon: "GitBranch",
    transport: "stdio",
    requiredEnv: [
      { key: "REPO_PATH", label: "Repository path", help: "Absolute path to a git working tree." },
    ],
    description: "A Model Context Protocol server providing tools to read, search, and manipulate Git repositories programmatically via LLMs",
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/git",
    command: "uvx",
    args: ["mcp-server-git", "--repository", "{{REPO_PATH}}"],
    official: true,
  },
  {
    id: "github",
    name: "GitHub",
    category: "development",
    icon: "Github",
    transport: "stdio",
    requiredEnv: [
      { key: "GITHUB_PERSONAL_ACCESS_TOKEN", label: "Personal access token", help: "github.com → Settings → Developer settings → Personal access tokens.", secret: true },
    ],
    description: "Issues, pull requests, code search and file contents across your repos.",
    docsUrl: "https://github.com/github/github-mcp-server",
    command: "npx",
    args: ["-y", "@github/mcp-server"],
    official: true,
  },
  {
    id: "gitlab",
    name: "GitLab",
    category: "development",
    icon: "Gitlab",
    transport: "stdio",
    requiredEnv: [
      { key: "GITLAB_PERSONAL_ACCESS_TOKEN", label: "Personal access token", secret: true },
      { key: "GITLAB_API_URL", label: "API URL", help: "Leave blank for gitlab.com.", optional: true, placeholder: "https://gitlab.com/api/v4" },
    ],
    description: "Projects, issues and merge requests on gitlab.com or self-hosted.",
    docsUrl: "https://gitlab.com/gitlab-org/gitlab-mcp-server",
    command: "npx",
    args: ["-y", "@gitlab/mcp-server"],
    official: true,
  },
  {
    id: "sentry",
    name: "Sentry",
    category: "development",
    icon: "Bug",
    transport: "stdio",
    requiredEnv: [
      { key: "SENTRY_AUTH_TOKEN", label: "Auth token", secret: true },
    ],
    description: "Pull issue details and stack traces from a Sentry project.",
    docsUrl: "https://github.com/getsentry/sentry-mcp",
    command: "npx",
    args: ["-y", "@sentry/mcp-server"],
    official: true,
  },
  {
    id: "postgres",
    name: "PostgreSQL",
    category: "data",
    icon: "Database",
    transport: "stdio",
    requiredEnv: [
      { key: "DATABASE_URL", label: "Connection string", help: "Queries are read-only. Prefer a least-privilege role.", secret: true, placeholder: "postgresql://user:pass@host:5432/db" },
    ],
    description: "Inspect schemas and run read-only queries against a Postgres database.",
    docsUrl: "https://github.com/henkey/postgres-mcp",
    command: "npx",
    args: ["-y", "@henkey/postgres-mcp", "{{DATABASE_URL}}"],
    official: false,
  },
  {
    id: "sqlite",
    name: "SQLite",
    category: "data",
    icon: "Database",
    transport: "stdio",
    requiredEnv: [
      { key: "DB_PATH", label: "Database file", placeholder: "./data.db" },
    ],
    description: "Query and describe a local SQLite database file.",
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/sqlite",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-sqlite", "--db-path", "{{DB_PATH}}"],
    official: false,
  },
  {
    id: "redis",
    name: "Redis",
    category: "data",
    icon: "Server",
    transport: "stdio",
    requiredEnv: [
      { key: "REDIS_URL", label: "Redis URL", secret: true, placeholder: "redis://localhost:6379" },
    ],
    description: "Read and write keys on a Redis instance.",
    docsUrl: "https://github.com/redis/mcp-redis",
    command: "npx",
    args: ["-y", "@redis/mcp-redis", "{{REDIS_URL}}"],
    official: true,
  },
  {
    id: "pglite",
    name: "PGlite",
    category: "data",
    icon: "Database",
    transport: "stdio",
    requiredEnv: [],
    description: "Run PostgreSQL in the browser or Node via PGlite, compiled to WASM.",
    docsUrl: "https://github.com/electric-sql/pglite-mcp",
    command: "npx",
    args: ["-y", "@electric-sql/pglite-mcp"],
    official: true,
  },
  {
    id: "brave-search",
    name: "Brave Search",
    category: "search",
    icon: "Search",
    transport: "stdio",
    requiredEnv: [
      { key: "BRAVE_API_KEY", label: "Brave API key", help: "Free tier available at brave.com/search/api.", secret: true },
    ],
    description: "Web and local search through the Brave Search API.",
    docsUrl: "https://github.com/brave/brave-search-mcp-server",
    command: "npx",
    args: ["-y", "@brave/brave-search-mcp-server"],
    official: true,
  },
  {
    id: "fetch",
    name: "Fetch",
    category: "search",
    icon: "Globe",
    transport: "stdio",
    requiredEnv: [],
    description: "A Model Context Protocol server providing tools to fetch and convert web content for usage by LLMs",
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/fetch",
    command: "uvx",
    args: ["mcp-server-fetch"],
    official: true,
  },
  {
    id: "context7",
    name: "Context7",
    category: "search",
    icon: "BookOpen",
    transport: "stdio",
    requiredEnv: [],
    description: "Inject up-to-date documentation for thousands of libraries into the model context.",
    docsUrl: "https://github.com/upstash/context7",
    command: "npx",
    args: ["-y", "@upstash/context7-mcp"],
    official: true,
  },
  {
    id: "exa",
    name: "Exa",
    category: "search",
    icon: "Search",
    transport: "stdio",
    requiredEnv: [
      { key: "EXA_API_KEY", label: "API key", secret: true },
    ],
    description: "Semantic and keyword web search over the live web, tuned for AI agents.",
    docsUrl: "https://github.com/exa-labs/exa-mcp-server",
    command: "npx",
    args: ["-y", "exa-mcp-server"],
    official: true,
  },
  {
    id: "tavily",
    name: "Tavily",
    category: "search",
    icon: "Search",
    transport: "stdio",
    requiredEnv: [
      { key: "TAVILY_API_KEY", label: "API key", secret: true },
    ],
    description: "Web search built for AI agents: clean, relevant results with context.",
    docsUrl: "https://github.com/tavily-ai/tavily-mcp",
    command: "npx",
    args: ["-y", "tavily-mcp"],
    official: true,
  },
  {
    id: "playwright",
    name: "Playwright",
    category: "automation",
    icon: "MousePointerClick",
    transport: "stdio",
    requiredEnv: [],
    description: "Drive a real browser with Playwright: navigate, click, fill forms and screenshot.",
    docsUrl: "https://github.com/microsoft/playwright-mcp",
    command: "npx",
    args: ["-y", "@playwright/mcp"],
    official: true,
  },
  {
    id: "chrome-devtools",
    name: "Chrome DevTools",
    category: "automation",
    icon: "Chrome",
    transport: "stdio",
    requiredEnv: [],
    description: "Drive Chrome via the DevTools Protocol: inspect pages, evaluate JS and capture traces.",
    docsUrl: "https://github.com/ChromeDevTools/chrome-devtools-mcp",
    command: "npx",
    args: ["-y", "chrome-devtools-mcp@latest"],
    official: true,
  },
  {
    id: "slack",
    name: "Slack",
    category: "productivity",
    icon: "MessageSquare",
    transport: "stdio",
    requiredEnv: [
      { key: "SLACK_BOT_TOKEN", label: "Bot token", help: "Starts with xoxb-.", secret: true },
      { key: "SLACK_TEAM_ID", label: "Team ID", placeholder: "T01234567" },
    ],
    description: "Read channels, post messages and search history in a workspace.",
    docsUrl: "https://github.com/zencoderai/slack-mcp-server",
    command: "npx",
    args: ["-y", "@zencoderai/slack-mcp-server"],
    official: false,
  },
  {
    id: "google-drive",
    name: "Google Drive",
    category: "productivity",
    icon: "HardDrive",
    transport: "stdio",
    requiredEnv: [
      { key: "GDRIVE_CREDENTIALS_PATH", label: "Credentials JSON path", help: "OAuth client credentials file. Requires uv (uvx) to be installed." },
    ],
    description: "List, search and read documents from Drive.",
    docsUrl: "https://github.com/googleapis/gdrive-mcp-server",
    command: "uvx",
    args: ["gdrive-mcp-server"],
    official: true,
  },
  {
    id: "notion",
    name: "Notion",
    category: "productivity",
    icon: "FileText",
    transport: "stdio",
    requiredEnv: [
      { key: "NOTION_API_KEY", label: "Integration token", help: "Create an internal integration and share the pages with it.", secret: true },
    ],
    description: "Search, read and update Notion pages and databases.",
    docsUrl: "https://github.com/makenotion/notion-mcp-server",
    command: "npx",
    args: ["-y", "@notionhq/notion-mcp-server"],
  },
  {
    id: "linear",
    name: "Linear",
    category: "productivity",
    icon: "ListTodo",
    transport: "stdio",
    requiredEnv: [
      { key: "LINEAR_API_KEY", label: "API key", secret: true },
    ],
    description: "Query and update Linear issues, projects and cycles.",
    docsUrl: "https://linear.app/docs/mcp",
    command: "npx",
    args: ["-y", "mcp-linear"],
  },
  {
    id: "todoist",
    name: "Todoist",
    category: "productivity",
    icon: "ListChecks",
    transport: "stdio",
    requiredEnv: [
      { key: "TODOIST_API_TOKEN", label: "API token", secret: true },
    ],
    description: "Manage Todoist tasks, projects, sections and labels.",
    docsUrl: "https://github.com/abhiz123/todoist-mcp-server",
    command: "npx",
    args: ["-y", "@abhiz123/todoist-mcp-server"],
    official: false,
  },
  {
    id: "figma",
    name: "Figma",
    category: "productivity",
    icon: "Figma",
    transport: "stdio",
    requiredEnv: [
      { key: "FIGMA_API_KEY", label: "Personal access token", secret: true, help: "Figma → Settings → Security → Personal access tokens." },
    ],
    description: "Inspect Figma files, frames, components and styles from a project.",
    docsUrl: "https://github.com/figma/figma-developer-mcp",
    command: "npx",
    args: ["-y", "figma-developer-mcp", "--figma-api-key={{FIGMA_API_KEY}}"],
    official: true,
  },
  {
    id: "aws",
    name: "AWS",
    category: "cloud",
    icon: "Cloud",
    transport: "stdio",
    requiredEnv: [
      { key: "AWS_ACCESS_KEY_ID", label: "Access key ID", secret: true },
      { key: "AWS_SECRET_ACCESS_KEY", label: "Secret access key", secret: true },
      { key: "AWS_REGION", label: "Region", placeholder: "us-east-1" },
    ],
    description: "Inspect AWS resources and run read-only API calls.",
    docsUrl: "https://github.com/modelcontextprotocol/servers-archived/tree/main/src/aws-kb-retrieval-server",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-aws-kb-retrieval"],
    official: false,
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    category: "cloud",
    icon: "Cloud",
    transport: "stdio",
    requiredEnv: [
      { key: "CLOUDFLARE_API_TOKEN", label: "API token", secret: true },
      { key: "CLOUDFLARE_ACCOUNT_ID", label: "Account ID" },
    ],
    description: "Manage Workers, KV, R2 and DNS on a Cloudflare account.",
    docsUrl: "https://github.com/cloudflare/mcp-server-cloudflare",
    command: "npx",
    args: ["-y", "@cloudflare/mcp-server-cloudflare"],
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    category: "cloud",
    icon: "Boxes",
    transport: "stdio",
    requiredEnv: [
      { key: "KUBECONFIG", label: "Kubeconfig path", help: "Leave blank to use the default ~/.kube/config.", optional: true },
    ],
    description: "Inspect cluster resources, pods, logs and events.",
    docsUrl: "https://github.com/Flux159/mcp-server-kubernetes",
    command: "npx",
    args: ["-y", "mcp-server-kubernetes"],
  },
  {
    id: "docker",
    name: "Docker",
    category: "cloud",
    icon: "Container",
    transport: "stdio",
    requiredEnv: [],
    description: "List containers and images, read logs, inspect the local daemon.",
    docsUrl: "https://github.com/QuantGeekDev/docker-mcp",
    command: "npx",
    args: ["-y", "docker-mcp"],
  },
  {
    id: "stripe",
    name: "Stripe",
    category: "cloud",
    icon: "CreditCard",
    transport: "http",
    requiredEnv: [
      { key: "STRIPE_API_KEY", label: "Restricted API key", secret: true, help: "dashboard.stripe.com → API keys → create restricted key. Sent as a Bearer token." },
    ],
    description: "Query and manage Stripe customers, payments, products and subscriptions.",
    docsUrl: "https://docs.stripe.com/mcp",
    url: "https://mcp.stripe.com",
    official: true,
  },
  {
    id: "supabase",
    name: "Supabase",
    category: "cloud",
    icon: "Server",
    transport: "http",
    requiredEnv: [
      { key: "SUPABASE_ACCESS_TOKEN", label: "Access token", secret: true, help: "Personal access token starting with sbp_. Sent as a Bearer token." },
    ],
    description: "Inspect and manage a Supabase project: tables, functions, storage and auth.",
    docsUrl: "https://supabase.com/docs/guides/mcp",
    url: "https://mcp.supabase.com/mcp",
    official: true,
  },
  {
    id: "memory",
    name: "Knowledge Graph Memory",
    category: "memory",
    icon: "Brain",
    transport: "stdio",
    requiredEnv: [],
    description: "MCP server for enabling memory for Claude through a knowledge graph",
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/memory",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-memory"],
    official: true,
  },
  {
    id: "sequential-thinking",
    name: "Sequential Thinking",
    category: "memory",
    icon: "Workflow",
    transport: "stdio",
    requiredEnv: [],
    description: "MCP server for sequential thinking and problem solving",
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-sequential-thinking"],
    official: true,
  },
  {
    id: "everything",
    name: "Everything (reference)",
    category: "development",
    icon: "TestTube",
    transport: "stdio",
    requiredEnv: [],
    description: "MCP server that exercises all the features of the MCP protocol",
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/everything",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-everything"],
    official: true,
  },
  {
    id: "time",
    name: "Time",
    category: "productivity",
    icon: "Clock",
    transport: "stdio",
    requiredEnv: [],
    description: "A Model Context Protocol server providing tools for time queries and timezone conversions for LLMs",
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/time",
    command: "uvx",
    args: ["mcp-server-time"],
    official: true,
  },
];

export const MCP_CATALOG_CATEGORIES: Record<McpCatalogCategory, string> = {
  development: 'Development',
  data: 'Data',
  productivity: 'Productivity',
  search: 'Search & Web',
  cloud: 'Cloud & Infra',
  automation: 'Automation',
  memory: 'Memory & Reasoning',
};

export function getCatalogEntry(id: string): McpCatalogEntry | undefined {
  return MCP_CATALOG.find((e) => e.id === id);
}

/**
 * Substitute `{{KEY}}` tokens in a catalog entry's args from supplied values.
 *
 * Some servers take a path or connection string as a positional argument
 * rather than an env var (filesystem, postgres, sqlite), so the same value the
 * operator typed has to be able to reach either place. A token with no
 * matching value is left intact so the failure surfaces in the connection test
 * rather than silently becoming the empty string — an empty allowlist path
 * would otherwise read as "current directory".
 */
export function renderCatalogArgs(args: string[] | undefined, values: Record<string, string>): string[] {
  if (!args) return [];
  return args.map((arg) =>
    arg.replace(/\{\{(\w+)\}\}/g, (whole, key: string) =>
      values[key] !== undefined && values[key] !== '' ? values[key] : whole,
    ),
  );
}
