/**
 * DMR-X Provider Catalog
 *
 * Complete list of supported AI providers with metadata.
 * This is the single source of truth for available providers.
 */
export const PROVIDER_CATALOG = [
    // === LLM Providers ===
    {
        id: 'openai',
        name: 'OpenAI',
        description: 'GPT-4o, GPT-4, o1/o3 reasoning models, DALL-E, Whisper, TTS',
        category: ['llm', 'image', 'audio_tts', 'audio_stt', 'embedding', 'moderation'],
        baseUrl: 'https://api.openai.com/v1',
        envKey: 'OPENAI_API_KEY',
        models: ['gpt-4o', 'gpt-4o-mini', 'gpt-4-turbo', 'o1', 'o1-mini', 'o3-mini', 'dall-e-3', 'whisper-1', 'tts-1', 'text-embedding-3-small', 'text-embedding-3-large'],
        freeModels: [],
        website: 'https://openai.com',
        docsUrl: 'https://platform.openai.com/docs',
        pricingUrl: 'https://openai.com/pricing',
    },
    {
        id: 'anthropic',
        name: 'Anthropic',
        description: 'Claude 3.5 Sonnet, Claude 3 Opus, Haiku - best for code and reasoning',
        category: ['llm'],
        baseUrl: 'https://api.anthropic.com/v1',
        envKey: 'ANTHROPIC_API_KEY',
        models: ['claude-3-5-sonnet-20241022', 'claude-3-5-haiku-20241022', 'claude-3-opus-20240229', 'claude-3-haiku-20240307'],
        freeModels: [],
        website: 'https://anthropic.com',
        docsUrl: 'https://docs.anthropic.com',
        pricingUrl: 'https://anthropic.com/pricing',
    },
    {
        id: 'google',
        name: 'Google AI',
        description: 'Gemini 1.5 Pro/Flash, Gemini 2.0 - multimodal, long context',
        category: ['llm', 'embedding'],
        baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
        envKey: 'GOOGLE_API_KEY',
        models: ['gemini-1.5-pro', 'gemini-1.5-flash', 'gemini-2.0-flash', 'gemini-2.0-flash-lite', 'text-embedding-004'],
        freeModels: ['gemini-1.5-flash', 'gemini-2.0-flash-lite'],
        website: 'https://ai.google.dev',
        docsUrl: 'https://ai.google.dev/docs',
        pricingUrl: 'https://ai.google.dev/pricing',
    },
    {
        id: 'groq',
        name: 'Groq',
        description: 'Ultra-fast inference on LPU hardware - Llama, Mixtral, Gemma',
        category: ['llm', 'audio_stt'],
        baseUrl: 'https://api.groq.com/openai/v1',
        envKey: 'GROQ_API_KEY',
        models: ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant', 'mixtral-8x7b-32768', 'gemma2-9b-it', 'whisper-large-v3'],
        freeModels: ['llama-3.1-8b-instant', 'gemma2-9b-it'],
        website: 'https://groq.com',
        docsUrl: 'https://console.groq.com/docs',
        pricingUrl: 'https://groq.com/pricing',
    },
    {
        id: 'mistral',
        name: 'Mistral AI',
        description: 'Mistral Large, Medium, Small - European AI, strong multilingual',
        category: ['llm', 'embedding'],
        baseUrl: 'https://api.mistral.ai/v1',
        envKey: 'MISTRAL_API_KEY',
        models: ['mistral-large-latest', 'mistral-medium-latest', 'mistral-small-latest', 'codestral-latest', 'open-mistral-nemo', 'mistral-embed'],
        freeModels: ['open-mistral-nemo'],
        website: 'https://mistral.ai',
        docsUrl: 'https://docs.mistral.ai',
        pricingUrl: 'https://mistral.ai/pricing',
    },
    {
        id: 'deepseek',
        name: 'DeepSeek',
        description: 'DeepSeek V3, Coder - excellent code generation, very cheap',
        category: ['llm'],
        baseUrl: 'https://api.deepseek.com/v1',
        envKey: 'DEEPSEEK_API_KEY',
        models: ['deepseek-chat', 'deepseek-coder', 'deepseek-reasoner'],
        freeModels: [],
        website: 'https://deepseek.com',
        docsUrl: 'https://platform.deepseek.com/api-docs',
        pricingUrl: 'https://deepseek.com/pricing',
    },
    {
        id: 'xai',
        name: 'xAI',
        description: 'Grok models - real-time knowledge, humor, X/Twitter integration',
        category: ['llm'],
        baseUrl: 'https://api.x.ai/v1',
        envKey: 'XAI_API_KEY',
        models: ['grok-2', 'grok-2-mini', 'grok-3'],
        freeModels: [],
        website: 'https://x.ai',
        docsUrl: 'https://docs.x.ai',
        pricingUrl: 'https://x.ai/pricing',
    },
    {
        id: 'cohere',
        name: 'Cohere',
        description: 'Command R+, Embed, Rerank - enterprise RAG specialist',
        category: ['llm', 'embedding', 'reranking'],
        baseUrl: 'https://api.cohere.com/v2',
        envKey: 'COHERE_API_KEY',
        models: ['command-r-plus', 'command-r', 'command-light', 'embed-english-v3.0', 'embed-multilingual-v3.0', 'rerank-english-v3.0', 'rerank-multilingual-v3.0'],
        freeModels: ['command-light'],
        website: 'https://cohere.com',
        docsUrl: 'https://docs.cohere.com',
        pricingUrl: 'https://cohere.com/pricing',
    },
    {
        id: 'together',
        name: 'Together AI',
        description: 'Open-source model hosting - Llama, Mixtral, CodeLlama, FLUX',
        category: ['llm', 'image', 'embedding'],
        baseUrl: 'https://api.together.xyz/v1',
        envKey: 'TOGETHER_API_KEY',
        models: ['meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo', 'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo', 'mistralai/Mixtral-8x7B-Instruct-v0.1', 'black-forest-labs/FLUX.1-schnell', 'togethercomputer/m2-bert-80M-8k-retrieval'],
        freeModels: ['meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo'],
        website: 'https://together.ai',
        docsUrl: 'https://docs.together.ai',
        pricingUrl: 'https://together.ai/pricing',
    },
    {
        id: 'fireworks',
        name: 'Fireworks AI',
        description: 'Fast open-source inference - Llama, Mixtral, function calling',
        category: ['llm', 'embedding'],
        baseUrl: 'https://api.fireworks.ai/inference/v1',
        envKey: 'FIREWORKS_API_KEY',
        models: ['accounts/fireworks/models/llama-v3p1-70b-instruct', 'accounts/fireworks/models/llama-v3p1-8b-instruct', 'accounts/fireworks/models/mixtral-8x7b-instruct', 'accounts/fireworks/models/nomic-embed-text-v1.5'],
        freeModels: [],
        website: 'https://fireworks.ai',
        docsUrl: 'https://docs.fireworks.ai',
        pricingUrl: 'https://fireworks.ai/pricing',
    },
    {
        id: 'cerebras',
        name: 'Cerebras',
        description: 'Wafer-speed inference - fastest Llama inference available',
        category: ['llm'],
        baseUrl: 'https://api.cerebras.ai/v1',
        envKey: 'CEREBRAS_API_KEY',
        models: ['llama3.1-8b', 'llama3.1-70b'],
        freeModels: ['llama3.1-8b'],
        website: 'https://cerebras.ai',
        docsUrl: 'https://inference-docs.cerebras.ai',
        pricingUrl: 'https://cerebras.ai/pricing',
    },
    {
        id: 'sambanova',
        name: 'SambaNova',
        description: 'RDU chip inference - fast open-source model serving',
        category: ['llm'],
        baseUrl: 'https://api.sambanova.ai/v1',
        envKey: 'SAMBANOVA_API_KEY',
        models: ['Meta-Llama-3.1-8B-Instruct', 'Meta-Llama-3.1-70B-Instruct', 'DeepSeek-V3'],
        freeModels: ['Meta-Llama-3.1-8B-Instruct'],
        website: 'https://sambanova.ai',
        docsUrl: 'https://docs.sambanova.ai',
        pricingUrl: 'https://sambanova.ai/pricing',
    },
    {
        id: 'perplexity',
        name: 'Perplexity',
        description: 'Search-augmented models - Sonar, online LLM with citations',
        category: ['llm'],
        baseUrl: 'https://api.perplexity.ai',
        envKey: 'PERPLEXITY_API_KEY',
        models: ['llama-3.1-sonar-small-128k-online', 'llama-3.1-sonar-large-128k-online', 'llama-3.1-sonar-huge-128k-online'],
        freeModels: [],
        website: 'https://perplexity.ai',
        docsUrl: 'https://docs.perplexity.ai',
        pricingUrl: 'https://perplexity.ai/pricing',
    },
    {
        id: 'replicate',
        name: 'Replicate',
        description: 'Run any open-source model - images, video, audio, LLMs',
        category: ['llm', 'image', 'video', 'audio_tts', 'music'],
        baseUrl: 'https://api.replicate.com/v1',
        envKey: 'REPLICATE_API_TOKEN',
        models: ['meta/llama-3.1-405b-instruct', 'black-forest-labs/flux-schnell', 'stability-ai/stable-diffusion-xl', 'minimax/video-01', 'suno-ai/bark'],
        freeModels: [],
        website: 'https://replicate.com',
        docsUrl: 'https://replicate.com/docs',
        pricingUrl: 'https://replicate.com/pricing',
    },
    {
        id: 'huggingface',
        name: 'Hugging Face',
        description: 'Open model hub inference API - thousands of models available',
        category: ['llm', 'image', 'embedding', 'audio_stt'],
        baseUrl: 'https://api-inference.huggingface.co/models',
        envKey: 'HUGGINGFACE_API_KEY',
        models: ['meta-llama/Meta-Llama-3.1-70B-Instruct', 'mistralai/Mistral-7B-Instruct-v0.3', 'stabilityai/stable-diffusion-xl-base-1.0', 'openai/whisper-large-v3'],
        freeModels: ['meta-llama/Meta-Llama-3.1-70B-Instruct'],
        website: 'https://huggingface.co',
        docsUrl: 'https://huggingface.co/docs/api-inference',
        pricingUrl: 'https://huggingface.co/pricing',
    },
    {
        id: 'novita',
        name: 'Novita AI',
        description: 'Affordable open-source model inference, Llama, Mixtral',
        category: ['llm', 'image'],
        baseUrl: 'https://api.novita.ai/v3/openai',
        envKey: 'NOVITA_API_KEY',
        models: ['meta-llama/llama-3.1-70b-instruct', 'mistralai/mixtral-8x7b-instruct', 'deepseek/deepseek-v3'],
        freeModels: [],
        website: 'https://novita.ai',
        docsUrl: 'https://novita.ai/docs',
        pricingUrl: 'https://novita.ai/pricing',
    },
    {
        id: 'openrouter',
        name: 'OpenRouter',
        description: 'Unified gateway to 100+ models - single key, automatic routing',
        category: ['llm', 'image'],
        baseUrl: 'https://openrouter.ai/api/v1',
        envKey: 'OPENROUTER_API_KEY',
        models: ['openai/gpt-4o', 'anthropic/claude-3.5-sonnet', 'meta-llama/llama-3.1-405b-instruct', 'google/gemini-1.5-pro', 'deepseek/deepseek-chat'],
        freeModels: ['meta-llama/llama-3.1-8b-instruct:free', 'google/gemma-2-9b-it:free'],
        website: 'https://openrouter.ai',
        docsUrl: 'https://openrouter.ai/docs',
        pricingUrl: 'https://openrouter.ai/models',
    },
    {
        id: 'voyage',
        name: 'Voyage AI',
        description: 'Best-in-class embedding models for RAG and search',
        category: ['embedding', 'reranking'],
        baseUrl: 'https://api.voyageai.com/v1',
        envKey: 'VOYAGE_API_KEY',
        models: ['voyage-3', 'voyage-3-lite', 'voyage-code-3', 'voyage-finance-2', 'voyage-law-2', 'rerank-2'],
        freeModels: [],
        website: 'https://voyageai.com',
        docsUrl: 'https://docs.voyageai.com',
        pricingUrl: 'https://voyageai.com/pricing',
    },
    {
        id: 'jina',
        name: 'Jina AI',
        description: 'Embeddings, reranking, reader - search infrastructure',
        category: ['embedding', 'reranking'],
        baseUrl: 'https://api.jina.ai/v1',
        envKey: 'JINA_API_KEY',
        models: ['jina-embeddings-v3', 'jina-reranker-v2-base-multilingual', 'jina-colbert-v2'],
        freeModels: [],
        website: 'https://jina.ai',
        docsUrl: 'https://jina.ai/reader',
        pricingUrl: 'https://jina.ai/pricing',
    },
    // === Image Generation ===
    {
        id: 'stability',
        name: 'Stability AI',
        description: 'Stable Diffusion 3, SDXL - open image generation',
        category: ['image'],
        baseUrl: 'https://api.stability.ai/v2beta',
        envKey: 'STABILITY_API_KEY',
        models: ['stable-diffusion-xl-1024-v1-0', 'stable-diffusion-512-v2-1', 'stable-core'],
        freeModels: [],
        website: 'https://stability.ai',
        docsUrl: 'https://platform.stability.ai/docs',
        pricingUrl: 'https://stability.ai/pricing',
    },
    {
        id: 'midjourney',
        name: 'Midjourney',
        description: 'Highest quality AI image generation (via API proxy)',
        category: ['image'],
        baseUrl: 'https://api.midjourney-proxy.com/v1',
        envKey: 'MIDJOURNEY_API_KEY',
        models: ['midjourney-v6', 'midjourney-v6.1', 'midjourney-niji-6'],
        freeModels: [],
        website: 'https://midjourney.com',
        docsUrl: 'https://docs.midjourney.com',
        pricingUrl: 'https://midjourney.com/pricing',
    },
    {
        id: 'ideogram',
        name: 'Ideogram',
        description: 'Text-in-image generation - best for logos and typography',
        category: ['image'],
        baseUrl: 'https://api.ideogram.ai/v1',
        envKey: 'IDEOGRAM_API_KEY',
        models: ['ideogram-v2', 'ideogram-v1'],
        freeModels: [],
        website: 'https://ideogram.ai',
        docsUrl: 'https://ideogram.ai/api',
        pricingUrl: 'https://ideogram.ai/pricing',
    },
    // === Audio - TTS ===
    {
        id: 'elevenlabs',
        name: 'ElevenLabs',
        description: 'Best AI voice generation - TTS, voice cloning, sound effects',
        category: ['audio_tts'],
        baseUrl: 'https://api.elevenlabs.io/v1',
        envKey: 'ELEVENLABS_API_KEY',
        models: ['eleven_multilingual_v2', 'eleven_turbo_v2', 'eleven_monolingual_v1'],
        freeModels: [],
        website: 'https://elevenlabs.io',
        docsUrl: 'https://elevenlabs.io/docs',
        pricingUrl: 'https://elevenlabs.io/pricing',
    },
    {
        id: 'playht',
        name: 'PlayHT',
        description: 'Real-time AI voice - TTS, voice cloning, conversational AI',
        category: ['audio_tts'],
        baseUrl: 'https://api.play.ht/api/v2',
        envKey: 'PLAYHT_API_KEY',
        models: ['PlayHT2.0', 'PlayHT2.0-turbo', 'Play3.0-mini'],
        freeModels: [],
        website: 'https://play.ht',
        docsUrl: 'https://docs.play.ht',
        pricingUrl: 'https://play.ht/pricing',
    },
    // === Audio - STT ===
    {
        id: 'deepgram',
        name: 'Deepgram',
        description: 'Fastest speech-to-text - real-time transcription, Nova-2',
        category: ['audio_stt'],
        baseUrl: 'https://api.deepgram.com/v1',
        envKey: 'DEEPGRAM_API_KEY',
        models: ['nova-2', 'nova-2-medical', 'whisper-large', 'whisper-medium'],
        freeModels: [],
        website: 'https://deepgram.com',
        docsUrl: 'https://developers.deepgram.com',
        pricingUrl: 'https://deepgram.com/pricing',
    },
    {
        id: 'assemblyai',
        name: 'AssemblyAI',
        description: 'Speech-to-text with summarization, sentiment, topics',
        category: ['audio_stt'],
        baseUrl: 'https://api.assemblyai.com/v2',
        envKey: 'ASSEMBLYAI_API_KEY',
        models: ['best', 'nano', 'slam-1'],
        freeModels: [],
        website: 'https://assemblyai.com',
        docsUrl: 'https://docs.assemblyai.com',
        pricingUrl: 'https://assemblyai.com/pricing',
    },
    // === Video ===
    {
        id: 'runway',
        name: 'Runway',
        description: 'Gen-3 Alpha - professional AI video generation',
        category: ['video'],
        baseUrl: 'https://api.dev.runwayml.com/v1',
        envKey: 'RUNWAY_API_KEY',
        models: ['gen-3-alpha', 'gen-3-alpha-turbo'],
        freeModels: [],
        website: 'https://runwayml.com',
        docsUrl: 'https://docs.runwayml.com',
        pricingUrl: 'https://runwayml.com/pricing',
    },
    {
        id: 'luma',
        name: 'Luma AI',
        description: 'Dream Machine - high quality video generation',
        category: ['video'],
        baseUrl: 'https://api.lumalabs.ai/dream-machine/v1',
        envKey: 'LUMA_API_KEY',
        models: ['dream-machine-1.5', 'dream-machine-1.0'],
        freeModels: [],
        website: 'https://lumalabs.ai',
        docsUrl: 'https://docs.lumalabs.ai',
        pricingUrl: 'https://lumalabs.ai/pricing',
    },
    {
        id: 'kling',
        name: 'Kling AI',
        description: 'Kuaishou video generation - realistic motion and physics',
        category: ['video'],
        baseUrl: 'https://api.klingai.com/v1',
        envKey: 'KLING_API_KEY',
        models: ['kling-v1', 'kling-v1.5'],
        freeModels: [],
        website: 'https://klingai.com',
        docsUrl: 'https://docs.klingai.com',
        pricingUrl: 'https://klingai.com/pricing',
    },
    // === Music ===
    {
        id: 'suno',
        name: 'Suno',
        description: 'AI music generation - full songs with vocals and instruments',
        category: ['music'],
        baseUrl: 'https://api.suno.ai/v1',
        envKey: 'SUNO_API_KEY',
        models: ['suno-v3.5', 'suno-v3'],
        freeModels: [],
        website: 'https://suno.com',
        docsUrl: 'https://suno.com/docs',
        pricingUrl: 'https://suno.com/pricing',
    },
    {
        id: 'udio',
        name: 'Udio',
        description: 'AI music creation - high quality, genre-diverse generation',
        category: ['music'],
        baseUrl: 'https://api.udio.com/v1',
        envKey: 'UDIO_API_KEY',
        models: ['udio-v1.5', 'udio-v1'],
        freeModels: [],
        website: 'https://udio.com',
        docsUrl: 'https://udio.com/docs',
        pricingUrl: 'https://udio.com/pricing',
    },
    // === Local Model Servers ===
    {
        id: 'ollama',
        name: 'Ollama',
        description: 'Run models locally - Llama, Mistral, Phi, Gemma, CodeLlama',
        category: ['llm', 'embedding'],
        baseUrl: 'http://localhost:11434/v1',
        envKey: '',
        models: ['llama3.1', 'llama3.2', 'mistral', 'mixtral', 'phi3', 'gemma2', 'codellama', 'qwen2.5', 'nomic-embed-text'],
        freeModels: ['llama3.1', 'llama3.2', 'mistral', 'mixtral', 'phi3', 'gemma2', 'codellama', 'qwen2.5', 'nomic-embed-text'],
        website: 'https://ollama.ai',
        docsUrl: 'https://ollama.ai/docs',
        pricingUrl: '',
    },
    {
        id: 'vllm',
        name: 'vLLM',
        description: 'High-throughput local LLM serving - PagedAttention, continuous batching',
        category: ['llm'],
        baseUrl: 'http://localhost:8000/v1',
        envKey: '',
        models: ['any-huggingface-model'],
        freeModels: ['any-huggingface-model'],
        website: 'https://vllm.ai',
        docsUrl: 'https://docs.vllm.ai',
        pricingUrl: '',
    },
    {
        id: 'llamacpp',
        name: 'llama.cpp',
        description: 'Lightweight local inference - GGUF models, CPU/GPU hybrid',
        category: ['llm'],
        baseUrl: 'http://localhost:8080/v1',
        envKey: '',
        models: ['any-gguf-model'],
        freeModels: ['any-gguf-model'],
        website: 'https://github.com/ggerganov/llama.cpp',
        docsUrl: 'https://github.com/ggerganov/llama.cpp/blob/master/README.md',
        pricingUrl: '',
    },
    {
        id: 'textgen',
        name: 'text-generation-webui',
        description: 'Oobabooga web UI - local model serving with multiple backends',
        category: ['llm'],
        baseUrl: 'http://localhost:5000/v1',
        envKey: '',
        models: ['any-loaded-model'],
        freeModels: ['any-loaded-model'],
        website: 'https://github.com/oobabooga/text-generation-webui',
        docsUrl: 'https://github.com/oobabooga/text-generation-webui/wiki',
        pricingUrl: '',
    },
    {
        id: 'comfyui',
        name: 'ComfyUI',
        description: 'Local image/video generation - node-based workflow, SD/FLUX',
        category: ['image', 'video'],
        baseUrl: 'http://localhost:8188/api',
        envKey: '',
        models: ['stable-diffusion-xl', 'stable-diffusion-3', 'flux-schnell', 'flux-dev'],
        freeModels: ['stable-diffusion-xl', 'stable-diffusion-3', 'flux-schnell', 'flux-dev'],
        website: 'https://github.com/comfyanonymous/ComfyUI',
        docsUrl: 'https://github.com/comfyanonymous/ComfyUI/wiki',
        pricingUrl: '',
    },
    {
        id: 'automatic1111',
        name: 'AUTOMATIC1111',
        description: 'Stable Diffusion WebUI - local image generation with extensions',
        category: ['image'],
        baseUrl: 'http://localhost:7860/sdapi/v1',
        envKey: '',
        models: ['any-sd-model'],
        freeModels: ['any-sd-model'],
        website: 'https://github.com/AUTOMATIC1111/stable-diffusion-webui',
        docsUrl: 'https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki',
        pricingUrl: '',
    },
];
/**
 * Get a provider by ID
 */
export function getProvider(id) {
    return PROVIDER_CATALOG.find((p) => p.id === id);
}
/**
 * Get all provider IDs
 */
export function getAllProviderIds() {
    return PROVIDER_CATALOG.map((p) => p.id);
}
/**
 * Get providers by category
 */
export function getProvidersByCategory(category) {
    return PROVIDER_CATALOG.filter((p) => p.category.includes(category));
}
/**
 * Search providers by name or description
 */
export function searchProviders(query) {
    const lower = query.toLowerCase();
    return PROVIDER_CATALOG.filter((p) => p.id.includes(lower) ||
        p.name.toLowerCase().includes(lower) ||
        p.description.toLowerCase().includes(lower));
}
//# sourceMappingURL=catalog.js.map