/**
 * DMR-X Provider Catalog
 *
 * Complete list of supported AI providers with metadata.
 * This is the single source of truth for available providers.
 */

export type ProviderCategory =
  | 'llm'
  | 'image'
  | 'audio_tts'
  | 'audio_stt'
  | 'video'
  | 'music'
  | 'embedding'
  | 'reranking'
  | 'moderation'
  | 'local'
  | 'multi';

export interface ProviderEntry {
  id: string;
  name: string;
  description: string;
  category: ProviderCategory[];
  baseUrl: string;
  envKey: string;
  models: string[];
  freeModels: string[];
  website: string;
  docsUrl: string;
  pricingUrl: string;
}

export const PROVIDER_CATALOG: ProviderEntry[] = [
  // === LLM Providers ===
  {
    id: 'openai',
    name: 'OpenAI',
    description: 'GPT-4o, GPT-4, o1/o3 reasoning models, DALL-E, Whisper, TTS',
    category: ['llm', 'image', 'audio_tts', 'audio_stt', 'embedding', 'moderation'],
    baseUrl: 'https://api.openai.com/v1',
    envKey: 'OPENAI_API_KEY',
    models: ['gpt-4o', 'gpt-4o-mini', 'gpt-4.1', 'gpt-4.1-mini', 'o3', 'o3-mini', 'o4-mini', 'dall-e-3', 'whisper-1', 'tts-1', 'text-embedding-3-small', 'text-embedding-3-large'],
    freeModels: [],
    website: 'https://openai.com',
    docsUrl: 'https://platform.openai.com/docs',
    pricingUrl: 'https://openai.com/pricing',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    description: 'Claude 3.5 Sonnet, Claude 3 Opus, Haiku - best for code and reasoning',
    category: ['llm'],
    baseUrl: 'https://api.anthropic.com/v1',
    envKey: 'ANTHROPIC_API_KEY',
    models: ['claude-opus-4-0520', 'claude-sonnet-4-0520', 'claude-3.5-sonnet', 'claude-3.5-haiku'],
    freeModels: [],
    website: 'https://anthropic.com',
    docsUrl: 'https://docs.anthropic.com',
    pricingUrl: 'https://anthropic.com/pricing',
  },
  {
    id: 'google',
    name: 'Google AI',
    description: 'Gemini 3/3.1/2.5/2.0 - multimodal, long context, free tier',
    category: ['llm', 'embedding'],
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    envKey: 'GOOGLE_API_KEY',
    models: ['gemini-3-flash', 'gemini-3.1-flash-lite', 'gemini-2.5-pro', 'gemini-2.5-flash', 'gemini-2.0-flash', 'text-embedding-004'],
    freeModels: ['gemini-3-flash', 'gemini-3.1-flash-lite', 'gemini-2.5-pro', 'gemini-2.5-flash', 'gemini-2.0-flash'],
    website: 'https://ai.google.dev',
    docsUrl: 'https://ai.google.dev/docs',
    pricingUrl: 'https://ai.google.dev/pricing',
  },
  {
    id: 'groq',
    name: 'Groq',
    description: 'Ultra-fast LPU inference - Llama 4, GPT-OSS, Qwen3, Compound, Whisper STT. 30 RPM free.',
    category: ['llm', 'audio_stt'],
    baseUrl: 'https://api.groq.com/openai/v1',
    envKey: 'GROQ_API_KEY',
    models: ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant', 'mixtral-8x7b-32768', 'llama-4-scout-17b-16e-instruct', 'openai/gpt-oss-120b', 'openai/gpt-oss-20b', 'qwen/qwen3-32b', 'groq/compound', 'moonshotai/kimi-k2-instruct', 'whisper-large-v3', 'whisper-large-v3-turbo'],
    freeModels: ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant', 'mixtral-8x7b-32768', 'llama-4-scout-17b-16e-instruct', 'openai/gpt-oss-120b', 'openai/gpt-oss-20b', 'qwen/qwen3-32b', 'groq/compound', 'moonshotai/kimi-k2-instruct', 'whisper-large-v3', 'whisper-large-v3-turbo'],
    website: 'https://groq.com',
    docsUrl: 'https://console.groq.com/docs',
    pricingUrl: 'https://groq.com/pricing',
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    description: 'Mistral Large, Medium, Small - European AI, strong multilingual',
    category: ['llm', 'embedding'],
    baseUrl: 'https://api.mistral.ai/v1',
    envKey: 'MISTRAL_API_KEY',
    models: ['mistral-large-latest', 'mistral-medium-latest', 'mistral-small-latest', 'codestral-latest', 'open-mistral-nemo', 'mistral-embed'],
    freeModels: ['open-mistral-nemo'],
    website: 'https://mistral.ai',
    docsUrl: 'https://docs.mistral.ai',
    pricingUrl: 'https://mistral.ai/pricing',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    description: 'DeepSeek V3, Coder - excellent code generation, very cheap',
    category: ['llm'],
    baseUrl: 'https://api.deepseek.com/v1',
    envKey: 'DEEPSEEK_API_KEY',
    models: ['deepseek-chat', 'deepseek-coder', 'deepseek-reasoner'],
    freeModels: [],
    website: 'https://deepseek.com',
    docsUrl: 'https://platform.deepseek.com/api-docs',
    pricingUrl: 'https://deepseek.com/pricing',
  },
  {
    id: 'xai',
    name: 'xAI',
    description: 'Grok models - real-time knowledge, humor, X/Twitter integration',
    category: ['llm'],
    baseUrl: 'https://api.x.ai/v1',
    envKey: 'XAI_API_KEY',
    models: ['grok-3', 'grok-3-mini'],
    freeModels: ['grok-3-mini'],
    website: 'https://x.ai',
    docsUrl: 'https://docs.x.ai',
    pricingUrl: 'https://x.ai/pricing',
  },
  {
    id: 'cohere',
    name: 'Cohere',
    description: 'Command R+, Aya Vision, Reasoning, Translate - enterprise RAG specialist',
    category: ['llm', 'embedding', 'reranking'],
    baseUrl: 'https://api.cohere.com/v2',
    envKey: 'COHERE_API_KEY',
    models: ['command-r-plus', 'command-r', 'command-light', 'c4ai-aya-vision-32b', 'command-a-reasoning-08-2025', 'command-a-vision-07-2025', 'command-a-translate-08-2025', 'command-r7b-arabic-02-2025', 'embed-english-v3.0', 'embed-multilingual-v3.0', 'rerank-english-v3.0', 'rerank-multilingual-v3.0'],
    freeModels: ['command-light', 'c4ai-aya-vision-32b', 'command-a-reasoning-08-2025', 'command-a-vision-07-2025', 'command-a-translate-08-2025', 'command-r7b-arabic-02-2025'],
    website: 'https://cohere.com',
    docsUrl: 'https://docs.cohere.com',
    pricingUrl: 'https://cohere.com/pricing',
  },
  {
    id: 'together',
    name: 'Together AI',
    description: 'Open-source model hosting - Llama, Mixtral, CodeLlama, FLUX',
    category: ['llm', 'image', 'embedding'],
    baseUrl: 'https://api.together.xyz/v1',
    envKey: 'TOGETHER_API_KEY',
    models: ['meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo', 'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo', 'mistralai/Mixtral-8x7B-Instruct-v0.1', 'black-forest-labs/FLUX.1-schnell', 'togethercomputer/m2-bert-80M-8k-retrieval'],
    freeModels: ['meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo'],
    website: 'https://together.ai',
    docsUrl: 'https://docs.together.ai',
    pricingUrl: 'https://together.ai/pricing',
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    description: 'Fast open-source inference - Llama, Mixtral, function calling',
    category: ['llm', 'embedding'],
    baseUrl: 'https://api.fireworks.ai/inference/v1',
    envKey: 'FIREWORKS_API_KEY',
    models: ['accounts/fireworks/models/llama-v3p1-70b-instruct', 'accounts/fireworks/models/llama-v3p1-8b-instruct', 'accounts/fireworks/models/mixtral-8x7b-instruct', 'accounts/fireworks/models/nomic-embed-text-v1.5'],
    freeModels: [],
    website: 'https://fireworks.ai',
    docsUrl: 'https://docs.fireworks.ai',
    pricingUrl: 'https://fireworks.ai/pricing',
  },
  {
    id: 'cerebras',
    name: 'Cerebras',
    description: 'Wafer-speed inference - 1M tokens/day free, 30 RPM. Fastest Llama inference.',
    category: ['llm'],
    baseUrl: 'https://api.cerebras.ai/v1',
    envKey: 'CEREBRAS_API_KEY',
    models: ['llama-3.1-8b', 'llama-3.1-70b', 'gpt-oss-120b', 'zai-glm-4.7'],
    freeModels: ['llama-3.1-8b', 'llama-3.1-70b', 'gpt-oss-120b', 'zai-glm-4.7'],
    website: 'https://cerebras.ai',
    docsUrl: 'https://inference-docs.cerebras.ai',
    pricingUrl: 'https://cerebras.ai/pricing',
  },
  {
    id: 'sambanova',
    name: 'SambaNova',
    description: 'RDU-accelerated inference - $5 free credit, fast Llama/DeepSeek.',
    category: ['llm'],
    baseUrl: 'https://api.sambanova.ai/v1',
    envKey: 'SAMBANOVA_API_KEY',
    models: ['Meta-Llama-3.3-70B-Instruct', 'Meta-Llama-3.1-8B-Instruct', 'Meta-Llama-3.1-70B-Instruct', 'DeepSeek-R1', 'DeepSeek-V3.1', 'Qwen2.5-72B-Instruct', 'Llama-4-Maverick-17B-128E-Instruct'],
    freeModels: ['Meta-Llama-3.3-70B-Instruct', 'Meta-Llama-3.1-8B-Instruct', 'Meta-Llama-3.1-70B-Instruct', 'DeepSeek-R1', 'DeepSeek-V3.1', 'Qwen2.5-72B-Instruct', 'Llama-4-Maverick-17B-128E-Instruct'],
    website: 'https://sambanova.ai',
    docsUrl: 'https://docs.sambanova.ai',
    pricingUrl: 'https://sambanova.ai/pricing',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    description: 'Search-augmented models - Sonar, online LLM with citations',
    category: ['llm'],
    baseUrl: 'https://api.perplexity.ai',
    envKey: 'PERPLEXITY_API_KEY',
    models: ['sonar', 'sonar-pro'],
    freeModels: ['sonar', 'sonar-pro'],
    website: 'https://perplexity.ai',
    docsUrl: 'https://docs.perplexity.ai',
    pricingUrl: 'https://perplexity.ai/pricing',
  },
  {
    id: 'replicate',
    name: 'Replicate',
    description: 'Run any open-source model - images, video, audio, LLMs',
    category: ['llm', 'image', 'video', 'audio_tts', 'music'],
    baseUrl: 'https://api.replicate.com/v1',
    envKey: 'REPLICATE_API_TOKEN',
    models: ['meta/llama-3.1-405b-instruct', 'black-forest-labs/flux-schnell', 'stability-ai/stable-diffusion-xl', 'minimax/video-01', 'suno-ai/bark'],
    freeModels: [],
    website: 'https://replicate.com',
    docsUrl: 'https://replicate.com/docs',
    pricingUrl: 'https://replicate.com/pricing',
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    description: 'Open model hub inference API - thousands of models available',
    category: ['llm', 'image', 'embedding', 'audio_stt'],
    baseUrl: 'https://router.huggingface.co/v1',
    envKey: 'HUGGINGFACE_API_KEY',
    models: ['meta-llama/Meta-Llama-3.1-70B-Instruct', 'mistralai/Mistral-7B-Instruct-v0.3', 'stabilityai/stable-diffusion-xl-base-1.0', 'openai/whisper-large-v3'],
    freeModels: ['meta-llama/Llama-3.3-70B-Instruct', 'Qwen/Qwen2.5-72B-Instruct', 'mistralai/Mistral-7B-Instruct-v0.3'],
    website: 'https://huggingface.co',
    docsUrl: 'https://huggingface.co/docs/api-inference',
    pricingUrl: 'https://huggingface.co/pricing',
  },
  {
    id: 'novita',
    name: 'Novita AI',
    description: 'Affordable open-source model inference, Llama, Mixtral',
    category: ['llm', 'image'],
    baseUrl: 'https://api.novita.ai/v3/openai',
    envKey: 'NOVITA_API_KEY',
    models: ['meta-llama/llama-3.1-70b-instruct', 'mistralai/mixtral-8x7b-instruct', 'deepseek/deepseek-v3'],
    freeModels: ['meta-llama/llama-3.1-8b-instruct'],
    website: 'https://novita.ai',
    docsUrl: 'https://novita.ai/docs',
    pricingUrl: 'https://novita.ai/pricing',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    description: 'Unified gateway to 100+ models - 25+ free models available',
    category: ['llm', 'image'],
    baseUrl: 'https://openrouter.ai/api/v1',
    envKey: 'OPENROUTER_API_KEY',
    models: ['openai/gpt-4o', 'anthropic/claude-3.5-sonnet', 'meta-llama/llama-3.1-405b-instruct', 'google/gemini-1.5-pro', 'deepseek/deepseek-chat'],
    freeModels: ['qwen/qwen3-coder:free', 'minimax/minimax-m2.5:free', 'nvidia/llama-3.1-nemotron-ultra-253b-v1:free', 'thudm/glm-4.7:free', 'openai/gpt-oss-20b:free', 'deepseek/deepseek-v4-flash:free', 'google/gemma-4-26b-a4b-it:free', 'google/gemma-4-31b-it:free', 'qwen/qwen3-next-80b-a3b-instruct:free', 'nvidia/nemotron-3-super-120b-a12b:free', 'openai/gpt-oss-120b:free', 'poolside/laguna-m.1:free', 'arcee-ai/trinity-large-thinking:free', 'liquid/lfm-2.5-1.2b-instruct:free', 'z-ai/glm-4.5-air:free', 'baidu/cobuddy:free'],
    website: 'https://openrouter.ai',
    docsUrl: 'https://openrouter.ai/docs',
    pricingUrl: 'https://openrouter.ai/models',
  },
  {
    id: 'voyage',
    name: 'Voyage AI',
    description: 'Best-in-class embedding models for RAG and search',
    category: ['embedding', 'reranking'],
    baseUrl: 'https://api.voyageai.com/v1',
    envKey: 'VOYAGE_API_KEY',
    models: ['voyage-3', 'voyage-3-lite', 'voyage-code-3', 'voyage-finance-2', 'voyage-law-2', 'rerank-2'],
    freeModels: [],
    website: 'https://voyageai.com',
    docsUrl: 'https://docs.voyageai.com',
    pricingUrl: 'https://voyageai.com/pricing',
  },
  {
    id: 'jina',
    name: 'Jina AI',
    description: 'Embeddings, reranking, reader - search infrastructure',
    category: ['embedding', 'reranking'],
    baseUrl: 'https://api.jina.ai/v1',
    envKey: 'JINA_API_KEY',
    models: ['jina-embeddings-v3', 'jina-reranker-v2-base-multilingual', 'jina-colbert-v2'],
    freeModels: ['jina-embeddings-v3'],
    website: 'https://jina.ai',
    docsUrl: 'https://jina.ai/reader',
    pricingUrl: 'https://jina.ai/pricing',
  },

  // === Image Generation ===
  {
    id: 'stability',
    name: 'Stability AI',
    description: 'Stable Diffusion 3, SDXL - open image generation',
    category: ['image'],
    baseUrl: 'https://api.stability.ai/v2beta',
    envKey: 'STABILITY_API_KEY',
    models: ['stable-diffusion-xl-1024-v1-0', 'stable-diffusion-512-v2-1', 'stable-core'],
    freeModels: ['stable-diffusion-xl-1024-v1-0'],
    website: 'https://stability.ai',
    docsUrl: 'https://platform.stability.ai/docs',
    pricingUrl: 'https://stability.ai/pricing',
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    description: 'Highest quality AI image generation (via API proxy)',
    category: ['image'],
    baseUrl: 'https://api.midjourney-proxy.com/v1',
    envKey: 'MIDJOURNEY_API_KEY',
    models: ['midjourney-v6', 'midjourney-v6.1', 'midjourney-niji-6'],
    freeModels: [],
    website: 'https://midjourney.com',
    docsUrl: 'https://docs.midjourney.com',
    pricingUrl: 'https://midjourney.com/pricing',
  },
  {
    id: 'ideogram',
    name: 'Ideogram',
    description: 'Text-in-image generation - best for logos and typography',
    category: ['image'],
    baseUrl: 'https://api.ideogram.ai/v1',
    envKey: 'IDEOGRAM_API_KEY',
    models: ['ideogram-v2', 'ideogram-v1'],
    freeModels: [],
    website: 'https://ideogram.ai',
    docsUrl: 'https://ideogram.ai/api',
    pricingUrl: 'https://ideogram.ai/pricing',
  },

  // === Audio - TTS ===
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    description: 'Best AI voice generation - TTS, voice cloning, sound effects',
    category: ['audio_tts'],
    baseUrl: 'https://api.elevenlabs.io/v1',
    envKey: 'ELEVENLABS_API_KEY',
    models: ['eleven_multilingual_v2', 'eleven_turbo_v2', 'eleven_monolingual_v1'],
    freeModels: ['eleven_multilingual_v2'],
    website: 'https://elevenlabs.io',
    docsUrl: 'https://elevenlabs.io/docs',
    pricingUrl: 'https://elevenlabs.io/pricing',
  },
  {
    id: 'playht',
    name: 'PlayHT',
    description: 'Real-time AI voice - TTS, voice cloning, conversational AI',
    category: ['audio_tts'],
    baseUrl: 'https://api.play.ht/api/v2',
    envKey: 'PLAYHT_API_KEY',
    models: ['PlayHT2.0', 'PlayHT2.0-turbo', 'Play3.0-mini'],
    freeModels: [],
    website: 'https://play.ht',
    docsUrl: 'https://docs.play.ht',
    pricingUrl: 'https://play.ht/pricing',
  },
  {
    id: 'cartesia',
    name: 'Cartesia',
    description: 'Cartesia real-time TTS. 10K chars/month free. ~50ms latency.',
    category: ['audio_tts'],
    baseUrl: 'https://api.cartesia.ai/v1',
    envKey: 'CARTESIA_API_KEY',
    models: ['sonic'],
    freeModels: ['sonic'],
    website: 'https://cartesia.ai',
    docsUrl: 'https://docs.cartesia.ai',
    pricingUrl: 'https://cartesia.ai/pricing',
  },

  // === Audio - STT ===
  {
    id: 'deepgram',
    name: 'Deepgram',
    description: 'Fastest speech-to-text - real-time transcription, Nova-2',
    category: ['audio_stt'],
    baseUrl: 'https://api.deepgram.com/v1',
    envKey: 'DEEPGRAM_API_KEY',
    models: ['nova-2', 'nova-2-medical', 'whisper-large', 'whisper-medium'],
    freeModels: ['nova-2'],
    website: 'https://deepgram.com',
    docsUrl: 'https://developers.deepgram.com',
    pricingUrl: 'https://deepgram.com/pricing',
  },
  {
    id: 'assemblyai',
    name: 'AssemblyAI',
    description: 'Speech-to-text with summarization, sentiment, topics',
    category: ['audio_stt'],
    baseUrl: 'https://api.assemblyai.com/v2',
    envKey: 'ASSEMBLYAI_API_KEY',
    models: ['best', 'nano', 'slam-1'],
    freeModels: [],
    website: 'https://assemblyai.com',
    docsUrl: 'https://docs.assemblyai.com',
    pricingUrl: 'https://assemblyai.com/pricing',
  },

  // === Video ===
  {
    id: 'runway',
    name: 'Runway',
    description: 'Gen-3 Alpha - professional AI video generation',
    category: ['video'],
    baseUrl: 'https://api.dev.runwayml.com/v1',
    envKey: 'RUNWAY_API_KEY',
    models: ['gen-3-alpha', 'gen-3-alpha-turbo'],
    freeModels: [],
    website: 'https://runwayml.com',
    docsUrl: 'https://docs.runwayml.com',
    pricingUrl: 'https://runwayml.com/pricing',
  },
  {
    id: 'luma',
    name: 'Luma AI',
    description: 'Dream Machine - high quality video generation',
    category: ['video'],
    baseUrl: 'https://api.lumalabs.ai/dream-machine/v1',
    envKey: 'LUMA_API_KEY',
    models: ['dream-machine-1.5', 'dream-machine-1.0'],
    freeModels: [],
    website: 'https://lumalabs.ai',
    docsUrl: 'https://docs.lumalabs.ai',
    pricingUrl: 'https://lumalabs.ai/pricing',
  },
  {
    id: 'kling',
    name: 'Kling AI',
    description: 'Kuaishou video generation - realistic motion and physics',
    category: ['video'],
    baseUrl: 'https://api.klingai.com/v1',
    envKey: 'KLING_API_KEY',
    models: ['kling-v1', 'kling-v1.5'],
    freeModels: [],
    website: 'https://klingai.com',
    docsUrl: 'https://docs.klingai.com',
    pricingUrl: 'https://klingai.com/pricing',
  },

  // === Music ===
  {
    id: 'suno',
    name: 'Suno',
    description: 'AI music generation - full songs with vocals and instruments',
    category: ['music'],
    baseUrl: 'https://api.suno.ai/v1',
    envKey: 'SUNO_API_KEY',
    models: ['suno-v3.5', 'suno-v3'],
    freeModels: [],
    website: 'https://suno.com',
    docsUrl: 'https://suno.com/docs',
    pricingUrl: 'https://suno.com/pricing',
  },
  {
    id: 'udio',
    name: 'Udio',
    description: 'AI music creation - high quality, genre-diverse generation',
    category: ['music'],
    baseUrl: 'https://api.udio.com/v1',
    envKey: 'UDIO_API_KEY',
    models: ['udio-v1.5', 'udio-v1'],
    freeModels: [],
    website: 'https://udio.com',
    docsUrl: 'https://udio.com/docs',
    pricingUrl: 'https://udio.com/pricing',
  },

  // === New Free-Tier Providers (added 2026-05-21) ===
  {
    id: 'scaleway',
    name: 'Scaleway Generative APIs',
    description: 'EU-based AI inference - Gemma, Llama, Qwen3, Whisper, embeddings. GDPR compliant.',
    category: ['llm', 'embedding', 'audio_stt'],
    baseUrl: 'https://api.scaleway.com/v1',
    envKey: 'SCALEWAY_API_KEY',
    models: ['gemma-3-27b-it', 'llama-3.3-70b-instruct', 'pixtral-12b', 'whisper-large-v3', 'qwen3-embedding-8b'],
    freeModels: ['gemma-3-27b-it', 'llama-3.3-70b-instruct', 'qwen3-30b-a3b', 'pixtral-12b', 'whisper-large-v3', 'qwen3-embedding-8b'],
    website: 'https://scaleway.com',
    docsUrl: 'https://console.scaleway.com/generative-api/models',
    pricingUrl: 'https://www.scaleway.com/en/pricing/',
  },
  {
    id: 'upstage',
    name: 'Upstage',
    description: 'Korean AI - Solar Pro/Mini models. $10 free credits for 3 months.',
    category: ['llm', 'embedding'],
    baseUrl: 'https://api.upstage.ai/v1',
    envKey: 'UPSTAGE_API_KEY',
    models: ['solar-pro', 'solar-mini'],
    freeModels: ['solar-pro', 'solar-mini'],
    website: 'https://upstage.ai',
    docsUrl: 'https://console.upstage.ai',
    pricingUrl: 'https://upstage.ai/pricing',
  },
  {
    id: 'vercel-ai',
    name: 'Vercel AI Gateway',
    description: 'AI routing gateway - $5/month recurring free tier. Routes to multiple providers.',
    category: ['llm'],
    baseUrl: 'https://ai-gateway.vercel.sh/v1',
    envKey: 'VERCEL_AI_API_KEY',
    models: ['gpt-4o', 'claude-3.5-sonnet'],
    freeModels: ['gpt-4o', 'claude-3.5-sonnet'],
    website: 'https://vercel.com',
    docsUrl: 'https://vercel.com/docs/ai-gateway',
    pricingUrl: 'https://vercel.com/pricing',
  },
  {
    id: 'inference-net',
    name: 'Inference.net',
    description: 'Open model inference - $1 free credits ($25 with survey).',
    category: ['llm'],
    baseUrl: 'https://api.inference.net/v1',
    envKey: 'INFERENCE_NET_API_KEY',
    models: ['meta-llama/llama-3.1-70b-instruct'],
    freeModels: ['meta-llama/llama-3.1-70b-instruct'],
    website: 'https://inference.net',
    docsUrl: 'https://inference.net/docs',
    pricingUrl: 'https://inference.net/pricing',
  },
  {
    id: 'nlp-cloud',
    name: 'NLP Cloud',
    description: 'NLP API - $15 free credits. Phone verification required.',
    category: ['llm'],
    baseUrl: 'https://api.nlpcloud.io/v1',
    envKey: 'NLPCLOUD_API_KEY',
    models: ['llama-3.1-70b'],
    freeModels: ['llama-3.1-70b'],
    website: 'https://nlpcloud.com',
    docsUrl: 'https://nlpcloud.com/docs',
    pricingUrl: 'https://nlpcloud.com/pricing',
  },
  {
    id: 'alibaba-cloud',
    name: 'Alibaba Cloud Model Studio',
    description: 'Alibaba Qwen models - 1M free tokens per model. International.',
    category: ['llm', 'embedding'],
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    envKey: 'ALIBABA_CLOUD_API_KEY',
    models: ['qwen-max', 'qwen-turbo', 'qwen-coder'],
    freeModels: ['qwen-max', 'qwen-turbo', 'qwen-coder'],
    website: 'https://alibabacloud.com',
    docsUrl: 'https://bailian.console.alibabacloud.com',
    pricingUrl: 'https://alibabacloud.com/pricing',
  },
  {
    id: 'qwen-dashscope',
    name: 'Qwen (DashScope)',
    description: 'Qwen DashScope. ~1M tok/day free turbo. Qwen Max, Turbo, Coder.',
    category: ['llm'],
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    envKey: 'DASHSCOPE_API_KEY',
    models: ['qwen-max', 'qwen-turbo', 'qwen-coder'],
    freeModels: ['qwen-max', 'qwen-turbo', 'qwen-coder'],
    website: 'https://dashscope.aliyuncs.com',
    docsUrl: 'https://help.aliyun.com/zh/dashscope/',
    pricingUrl: 'https://help.aliyun.com/zh/dashscope/pricing',
  },
  {
    id: 'modal',
    name: 'Modal',
    description: 'Modal GPU compute. $30/month free. Run any self-hosted model on A100/H100.',
    category: ['llm'],
    baseUrl: 'https://modal.run/v1',
    envKey: 'MODAL_API_KEY',
    models: ['any-model'],
    freeModels: ['any-model'],
    website: 'https://modal.com',
    docsUrl: 'https://modal.com/docs',
    pricingUrl: 'https://modal.com/pricing',
  },
  {
    id: 'codestral-free',
    name: 'Mistral Codestral (Free)',
    description: 'Free Codestral endpoint - code-focused. 30 RPM, 2000 RPD.',
    category: ['llm'],
    baseUrl: 'https://codestral.mistral.ai/v1',
    envKey: 'CODESTRAL_API_KEY',
    models: ['codestral-latest'],
    freeModels: ['codestral-latest'],
    website: 'https://mistral.ai',
    docsUrl: 'https://docs.mistral.ai',
    pricingUrl: 'https://mistral.ai/pricing',
  },
  {
    id: 'opencode-zen',
    name: 'OpenCode Zen',
    description: 'Free AI gateway with curated models. Data may be used for training.',
    category: ['llm'],
    baseUrl: 'https://api.opencode.ai/v1',
    envKey: 'OPENCODE_ZEN_API_KEY',
    models: ['minimax-m2.5-free'],
    freeModels: ['minimax-m2.5-free'],
    website: 'https://opencode.ai',
    docsUrl: 'https://opencode.ai/docs',
    pricingUrl: '',
  },

  // === Additional Providers (from exhaustive research 2026-05-21) ===
  {
    id: 'bytedance',
    name: 'ByteDance (Doubao)',
    description: 'ByteDance Doubao/Seed models. TikTok parent. Cheap pricing.',
    category: ['llm'],
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    envKey: 'BYTEDANCE_API_KEY',
    models: ['seed-2.0-lite', 'doubao-pro'],
    freeModels: ['seed-2.0-lite'],
    website: 'https://volcengine.com',
    docsUrl: 'https://www.volcengine.com/docs/82379',
    pricingUrl: 'https://www.volcengine.com/pricing',
  },
  {
    id: 'baidu',
    name: 'Baidu (Ernie)',
    description: 'Baidu Ernie. Free ERNIE Speed/Lite. Strong Chinese language.',
    category: ['llm'],
    baseUrl: 'https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop',
    envKey: 'BAIDU_API_KEY',
    models: ['ernie-4.5', 'ernie-speed', 'ernie-lite'],
    freeModels: ['ernie-speed', 'ernie-lite'],
    website: 'https://cloud.baidu.com',
    docsUrl: 'https://cloud.baidu.com/doc/WENXINWORKSHOP',
    pricingUrl: 'https://cloud.baidu.com/pricing',
  },
  {
    id: 'yi',
    name: '01.AI (Yi)',
    description: '01.AI Yi models. Yi-Spark is free. Founded by Kai-Fu Lee.',
    category: ['llm'],
    baseUrl: 'https://api.lingyiwanwu.com/v1',
    envKey: 'YI_API_KEY',
    models: ['yi-spark', 'yi-large', 'yi-vision'],
    freeModels: ['yi-spark'],
    website: 'https://lingyiwanwu.com',
    docsUrl: 'https://platform.lingyiwanwu.com/docs',
    pricingUrl: 'https://platform.lingyiwanwu.com/pricing',
  },
  {
    id: 'iflytek',
    name: 'iFlytek (Spark)',
    description: 'iFlytek Spark. Free Spark Lite. China\'s leading speech AI.',
    category: ['llm', 'audio_stt', 'audio_tts'],
    baseUrl: 'https://spark-api-open.xf-yun.com/v1',
    envKey: 'IFLYTEK_API_KEY',
    models: ['spark-lite', 'spark-pro', 'spark-max'],
    freeModels: ['spark-lite'],
    website: 'https://xinghuo.xfyun.cn',
    docsUrl: 'https://www.xfyun.cn/doc/spark',
    pricingUrl: 'https://www.xfyun.cn/pricing',
  },
  {
    id: 'baichuan',
    name: 'Baichuan',
    description: 'Baichuan models. Strong Chinese NLP.',
    category: ['llm'],
    baseUrl: 'https://api.baichuan-ai.com/v1',
    envKey: 'BAICHUAN_API_KEY',
    models: ['baichuan4', 'baichuan3-turbo'],
    freeModels: [],
    website: 'https://baichuan-ai.com',
    docsUrl: 'https://platform.baichuan-ai.com/docs',
    pricingUrl: 'https://platform.baichuan-ai.com/pricing',
  },
  {
    id: 'tencent',
    name: 'Tencent (Hunyuan)',
    description: 'Tencent Hunyuan. WeChat ecosystem integration.',
    category: ['llm'],
    baseUrl: 'https://hunyuan.tencentcloudapi.com',
    envKey: 'TENCENT_API_KEY',
    models: ['hunyuan-pro', 'hunyuan-standard', 'hunyuan-lite'],
    freeModels: ['hunyuan-lite'],
    website: 'https://cloud.tencent.com',
    docsUrl: 'https://cloud.tencent.com/document/product/1729',
    pricingUrl: 'https://cloud.tencent.com/pricing',
  },
  {
    id: 'ai21',
    name: 'AI21 Labs',
    description: 'AI21 Jamba. Mamba-based hybrid. Long context.',
    category: ['llm'],
    baseUrl: 'https://api.ai21.com/v1',
    envKey: 'AI21_API_KEY',
    models: ['jamba-1.5', 'jurassic-2'],
    freeModels: [],
    website: 'https://ai21.com',
    docsUrl: 'https://docs.ai21.com',
    pricingUrl: 'https://ai21.com/pricing',
  },
  {
    id: 'featherless',
    name: 'Featherless AI',
    description: '4000+ open-source models serverless.',
    category: ['llm'],
    baseUrl: 'https://api.featherless.ai/v1',
    envKey: 'FEATHERLESS_API_KEY',
    models: ['meta-llama/llama-3.3-70b-instruct'],
    freeModels: [],
    website: 'https://featherless.ai',
    docsUrl: 'https://featherless.ai/docs',
    pricingUrl: 'https://featherless.ai/pricing',
  },
  {
    id: 'nomic',
    name: 'Nomic AI',
    description: 'Open-source embeddings. Atlas platform. Free tier.',
    category: ['embedding'],
    baseUrl: 'https://api-atlas.nomic.ai/v1',
    envKey: 'NOMIC_API_KEY',
    models: ['nomic-embed-text-v1.5'],
    freeModels: ['nomic-embed-text-v1.5'],
    website: 'https://nomic.ai',
    docsUrl: 'https://docs.nomic.ai',
    pricingUrl: 'https://nomic.ai/pricing',
  },
  {
    id: 'fal',
    name: 'FAL.ai',
    description: 'Fast diffusion/video/audio inference. Free credits.',
    category: ['image', 'video', 'audio_tts'],
    baseUrl: 'https://fal.run',
    envKey: 'FAL_API_KEY',
    models: ['flux/schnell', 'flux/dev'],
    freeModels: [],
    website: 'https://fal.ai',
    docsUrl: 'https://fal.ai/docs',
    pricingUrl: 'https://fal.ai/pricing',
  },
  {
    id: 'sensenova',
    name: 'SenseTime (SenseNova)',
    description: 'SenseTime SenseNova. Computer vision leader. Strong multimodal.',
    category: ['llm'],
    baseUrl: 'https://api.sensenova.cn/v1',
    envKey: 'SENSENOVA_API_KEY',
    models: ['sensechat-5', 'sensechat-4'],
    freeModels: [],
    website: 'https://sensenova.cn',
    docsUrl: 'https://platform.sensenova.cn/docs',
    pricingUrl: 'https://platform.sensenova.cn/pricing',
  },
  {
    id: 'watsonx',
    name: 'IBM watsonx.ai',
    description: 'IBM watsonx. Granite models. Lite plan with limited usage.',
    category: ['llm'],
    baseUrl: 'https://us-south.ml.cloud.ibm.com/ml/v1',
    envKey: 'WATSONX_API_KEY',
    models: ['granite-4.1-8b-instruct', 'granite-4.0-micro'],
    freeModels: ['granite-4.1-8b-instruct'],
    website: 'https://ibm.com/watsonx',
    docsUrl: 'https://ibm.com/docs/en/watsonx',
    pricingUrl: 'https://ibm.com/pricing',
  },
  {
    id: 'bedrock',
    name: 'Amazon Bedrock',
    description: 'AWS multi-model gateway. Claude, Llama, Mistral, Titan.',
    category: ['llm', 'embedding'],
    baseUrl: 'https://bedrock-runtime.us-east-1.amazonaws.com',
    envKey: 'AWS_ACCESS_KEY_ID',
    models: ['anthropic.claude-3-5-sonnet', 'meta.llama3-3-70b'],
    freeModels: [],
    website: 'https://aws.amazon.com/bedrock',
    docsUrl: 'https://docs.aws.amazon.com/bedrock',
    pricingUrl: 'https://aws.amazon.com/bedrock/pricing',
  },
  {
    id: 'azure-openai',
    name: 'Azure OpenAI',
    description: 'Azure OpenAI. Enterprise-grade. Regional deployments.',
    category: ['llm', 'embedding', 'audio_stt', 'audio_tts', 'image'],
    baseUrl: 'https://{resource}.openai.azure.com/openai',
    envKey: 'AZURE_OPENAI_API_KEY',
    models: ['gpt-4o', 'gpt-4.1', 'dall-e-3', 'whisper-1'],
    freeModels: [],
    website: 'https://azure.microsoft.com/openai',
    docsUrl: 'https://learn.microsoft.com/azure/ai-services/openai',
    pricingUrl: 'https://azure.microsoft.com/pricing',
  },
  {
    id: 'lepton',
    name: 'Lepton AI',
    description: 'Serverless GPU inference. Free credits on signup.',
    category: ['llm'],
    baseUrl: 'https://api.lepton.ai/v1',
    envKey: 'LEPTON_API_KEY',
    models: ['llama-3.3-70b'],
    freeModels: [],
    website: 'https://lepton.ai',
    docsUrl: 'https://lepton.ai/docs',
    pricingUrl: 'https://lepton.ai/pricing',
  },
  {
    id: 'baseten',
    name: 'Baseten',
    description: 'Model deployment platform. Truss framework.',
    category: ['llm'],
    baseUrl: 'https://model-{id}.api.baseten.co/production',
    envKey: 'BASETEN_API_KEY',
    models: ['llama-3.3-70b'],
    freeModels: [],
    website: 'https://baseten.co',
    docsUrl: 'https://docs.baseten.co',
    pricingUrl: 'https://baseten.co/pricing',
  },
  {
    id: 'reka',
    name: 'Reka AI',
    description: 'Founded by ex-Google DeepMind researchers.',
    category: ['llm'],
    baseUrl: 'https://api.reka.ai/v1',
    envKey: 'REKA_API_KEY',
    models: ['reka-edge', 'reka-flash'],
    freeModels: [],
    website: 'https://reka.ai',
    docsUrl: 'https://docs.reka.ai',
    pricingUrl: 'https://reka.ai/pricing',
  },
  {
    id: 'aleph-alpha',
    name: 'Aleph Alpha',
    description: 'European sovereignty AI. GDPR-compliant.',
    category: ['llm'],
    baseUrl: 'https://api.aleph-alpha.com',
    envKey: 'ALEPH_ALPHA_API_KEY',
    models: ['luminous-base', 'luminous-supreme'],
    freeModels: [],
    website: 'https://aleph-alpha.com',
    docsUrl: 'https://docs.aleph-alpha.com',
    pricingUrl: 'https://aleph-alpha.com/pricing',
  },
  {
    id: 'sarvam',
    name: 'Sarvam AI',
    description: 'India AI. 10+ Indian languages. Free tier.',
    category: ['llm', 'audio_stt', 'audio_tts'],
    baseUrl: 'https://api.sarvam.ai',
    envKey: 'SARVAM_API_KEY',
    models: ['sarvam-2b'],
    freeModels: ['sarvam-2b'],
    website: 'https://sarvam.ai',
    docsUrl: 'https://docs.sarvam.ai',
    pricingUrl: 'https://sarvam.ai/pricing',
  },
  {
    id: 'lmstudio',
    name: 'LM Studio',
    description: 'Desktop app for local models. Beautiful UI.',
    category: ['llm'],
    baseUrl: 'http://localhost:1234/v1',
    envKey: '',
    models: ['any-gguf-model'],
    freeModels: ['any-gguf-model'],
    website: 'https://lmstudio.ai',
    docsUrl: 'https://lmstudio.ai/docs',
    pricingUrl: '',
  },
  {
    id: 'jan',
    name: 'Jan',
    description: 'Open-source local AI. Desktop app.',
    category: ['llm'],
    baseUrl: 'http://localhost:1337/v1',
    envKey: '',
    models: ['any-model'],
    freeModels: ['any-model'],
    website: 'https://jan.ai',
    docsUrl: 'https://jan.ai/docs',
    pricingUrl: '',
  },

  // === Local Model Servers ===
  {
    id: 'ollama',
    name: 'Ollama',
    description: 'Run models locally - Llama, Mistral, Phi, Gemma, CodeLlama',
    category: ['llm', 'embedding'],
    baseUrl: 'http://localhost:11434/v1',
    envKey: '',
    models: ['llama3.1', 'llama3.2', 'mistral', 'mixtral', 'phi3', 'gemma2', 'codellama', 'qwen2.5', 'nomic-embed-text'],
    freeModels: ['llama3.1', 'llama3.2', 'mistral', 'mixtral', 'phi3', 'gemma2', 'codellama', 'qwen2.5', 'nomic-embed-text'],
    website: 'https://ollama.ai',
    docsUrl: 'https://ollama.ai/docs',
    pricingUrl: '',
  },
  {
    id: 'vllm',
    name: 'vLLM',
    description: 'High-throughput local LLM serving - PagedAttention, continuous batching',
    category: ['llm'],
    baseUrl: 'http://localhost:8000/v1',
    envKey: '',
    models: ['any-huggingface-model'],
    freeModels: ['any-huggingface-model'],
    website: 'https://vllm.ai',
    docsUrl: 'https://docs.vllm.ai',
    pricingUrl: '',
  },
  {
    id: 'llamacpp',
    name: 'llama.cpp',
    description: 'Lightweight local inference - GGUF models, CPU/GPU hybrid',
    category: ['llm'],
    baseUrl: 'http://localhost:8080/v1',
    envKey: '',
    models: ['any-gguf-model'],
    freeModels: ['any-gguf-model'],
    website: 'https://github.com/ggerganov/llama.cpp',
    docsUrl: 'https://github.com/ggerganov/llama.cpp/blob/master/README.md',
    pricingUrl: '',
  },
  {
    id: 'textgen',
    name: 'text-generation-webui',
    description: 'Oobabooga web UI - local model serving with multiple backends',
    category: ['llm'],
    baseUrl: 'http://localhost:5000/v1',
    envKey: '',
    models: ['any-loaded-model'],
    freeModels: ['any-loaded-model'],
    website: 'https://github.com/oobabooga/text-generation-webui',
    docsUrl: 'https://github.com/oobabooga/text-generation-webui/wiki',
    pricingUrl: '',
  },
  {
    id: 'comfyui',
    name: 'ComfyUI',
    description: 'Local image/video generation - node-based workflow, SD/FLUX',
    category: ['image', 'video'],
    baseUrl: 'http://localhost:8188/api',
    envKey: '',
    models: ['stable-diffusion-xl', 'stable-diffusion-3', 'flux-schnell', 'flux-dev'],
    freeModels: ['stable-diffusion-xl', 'stable-diffusion-3', 'flux-schnell', 'flux-dev'],
    website: 'https://github.com/comfyanonymous/ComfyUI',
    docsUrl: 'https://github.com/comfyanonymous/ComfyUI/wiki',
    pricingUrl: '',
  },
  {
    id: 'automatic1111',
    name: 'AUTOMATIC1111',
    description: 'Stable Diffusion WebUI - local image generation with extensions',
    category: ['image'],
    baseUrl: 'http://localhost:7860/sdapi/v1',
    envKey: '',
    models: ['any-sd-model'],
    freeModels: ['any-sd-model'],
    website: 'https://github.com/AUTOMATIC1111/stable-diffusion-webui',
    docsUrl: 'https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki',
    pricingUrl: '',
  },

  // === Providers from registry (added 2026-05-21 reconciliation) ===
  {
    id: 'nvidia-nim',
    name: 'NVIDIA NIM',
    description: 'NVIDIA NIM free tier. Llama, DeepSeek, Mistral on NVIDIA GPUs.',
    category: ['llm'],
    baseUrl: 'https://integrate.api.nvidia.com/v1',
    envKey: 'NVIDIA_NIM_API_KEY',
    models: ['meta/llama-3.1-8b-instruct', 'meta/llama-3.3-70b-instruct', 'meta/llama-4-maverick-17b-128e-instruct', 'deepseek-ai/deepseek-r1', 'mistralai/mistral-large-3-675b-instruct'],
    freeModels: ['meta/llama-3.1-8b-instruct', 'meta/llama-3.3-70b-instruct', 'meta/llama-4-maverick-17b-128e-instruct', 'deepseek-ai/deepseek-r1', 'mistralai/mistral-large-3-675b-instruct'],
    website: 'https://build.nvidia.com',
    docsUrl: 'https://docs.api.nvidia.com',
    pricingUrl: 'https://build.nvidia.com/pricing',
  },
  {
    id: 'github-models',
    name: 'GitHub Models',
    description: 'GitHub Models free tier. GPT-5, GPT-4.1, Grok 3, Llama 4, Mistral Medium.',
    category: ['llm', 'embedding'],
    baseUrl: 'https://models.inference.ai.azure.com',
    envKey: 'GITHUB_TOKEN',
    models: ['gpt-5', 'gpt-5-mini', 'gpt-4o-mini', 'gpt-4o', 'gpt-4.1', 'gpt-4.1-mini', 'grok-3', 'llama-4-maverick-17b-128e-instruct', 'mistral-medium-2505', 'text-embedding-3-small'],
    freeModels: ['gpt-5', 'gpt-5-mini', 'gpt-4o-mini', 'gpt-4o', 'gpt-4.1', 'gpt-4.1-mini', 'grok-3', 'llama-4-maverick-17b-128e-instruct', 'mistral-medium-2505', 'text-embedding-3-small'],
    website: 'https://github.com/marketplace/models',
    docsUrl: 'https://docs.github.com/en/github-models',
    pricingUrl: '',
  },
  {
    id: 'cloudflare-ai',
    name: 'Cloudflare Workers AI',
    description: 'Cloudflare Workers AI free tier. 10M neurons/day. Kimi K2.5/K2.6, GPT-OSS, SEA Lion.',
    category: ['llm'],
    baseUrl: 'https://api.cloudflare.com/client/v4/accounts/{ACCOUNT_ID}/ai/v1',
    envKey: 'CLOUDFLARE_AI_TOKEN',
    models: ['@cf/meta/llama-3.3-70b-instruct-fp8', '@cf/meta/llama-4-scout-17b-16e-instruct', '@cf/deepseek-ai/deepseek-r1-distill-qwen-32b', '@cf/qwen/qwen3-30b-a3b', '@cf/ibm-granite/granite-4.0-micro', '@cf/moonshotai/kimi-k2.5', '@cf/moonshotai/kimi-k2.6', '@cf/openai/gpt-oss-120b', '@cf/openai/gpt-oss-20b', '@cf/aisingapore/gemma-sea-lion-v4-27b-it', '@cf/zai-org/glm-4.7-flash'],
    freeModels: ['@cf/meta/llama-3.3-70b-instruct-fp8', '@cf/meta/llama-4-scout-17b-16e-instruct', '@cf/deepseek-ai/deepseek-r1-distill-qwen-32b', '@cf/qwen/qwen3-30b-a3b', '@cf/ibm-granite/granite-4.0-micro', '@cf/moonshotai/kimi-k2.5', '@cf/moonshotai/kimi-k2.6', '@cf/openai/gpt-oss-120b', '@cf/openai/gpt-oss-20b', '@cf/aisingapore/gemma-sea-lion-v4-27b-it', '@cf/zai-org/glm-4.7-flash'],
    website: 'https://developers.cloudflare.com/workers-ai',
    docsUrl: 'https://developers.cloudflare.com/workers-ai',
    pricingUrl: 'https://developers.cloudflare.com/workers-ai/pricing',
  },
  {
    id: 'zhipu',
    name: 'Zhipu (Z.ai)',
    description: 'Zhipu GLM models. Chinese LLM with free tier.',
    category: ['llm'],
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    envKey: 'ZHIPU_API_KEY',
    models: ['glm-4.5-flash', 'glm-4.7-flash', 'glm-4-plus', 'glm-4-0520', 'glm-4-flash', 'glm-4-air', 'glm-4-long', 'glm-4-flashx', 'glm-4-alltools', 'glm-4v-plus', 'glm-4v-flash', 'cogvideox-flash', 'cogvideox', 'embedding-3'],
    freeModels: ['glm-4.5-flash', 'glm-4.7-flash'],
    website: 'https://open.bigmodel.cn',
    docsUrl: 'https://open.bigmodel.cn/dev/howuse/introduction',
    pricingUrl: 'https://open.bigmodel.cn/pricing',
  },
  {
    id: 'openrouter-free',
    name: 'OpenRouter (Free)',
    description: 'OpenRouter free models. 25+ free-tier models including GPT-OSS, Gemma 4, Qwen3, DeepSeek V4.',
    category: ['llm'],
    baseUrl: 'https://openrouter.ai/api/v1',
    envKey: 'OPENROUTER_API_KEY',
    models: ['qwen/qwen3-coder:free', 'minimax/minimax-m2.5:free', 'nvidia/llama-3.1-nemotron-ultra-253b-v1:free', 'thudm/glm-4.7:free', 'openai/gpt-oss-20b:free', 'deepseek/deepseek-v4-flash:free', 'google/gemma-4-26b-a4b-it:free', 'google/gemma-4-31b-it:free', 'qwen/qwen3-next-80b-a3b-instruct:free', 'nvidia/nemotron-3-super-120b-a12b:free', 'openai/gpt-oss-120b:free', 'poolside/laguna-m.1:free', 'arcee-ai/trinity-large-thinking:free', 'liquid/lfm-2.5-1.2b-instruct:free', 'z-ai/glm-4.5-air:free', 'baidu/cobuddy:free', 'mistralai/mistral-nemo-12b-instruct:free', 'meta-llama/llama-3.3-70b-instruct:free', 'meta-llama/llama-3.1-8b-instruct:free', 'huggingfaceh4/zephyr-7b-beta:free', 'nousresearch/hermes-3-llama-3.1-405b:free'],
    freeModels: ['qwen/qwen3-coder:free', 'minimax/minimax-m2.5:free', 'nvidia/llama-3.1-nemotron-ultra-253b-v1:free', 'thudm/glm-4.7:free', 'openai/gpt-oss-20b:free', 'deepseek/deepseek-v4-flash:free', 'google/gemma-4-26b-a4b-it:free', 'google/gemma-4-31b-it:free', 'qwen/qwen3-next-80b-a3b-instruct:free', 'nvidia/nemotron-3-super-120b-a12b:free', 'openai/gpt-oss-120b:free', 'poolside/laguna-m.1:free', 'arcee-ai/trinity-large-thinking:free', 'liquid/lfm-2.5-1.2b-instruct:free', 'z-ai/glm-4.5-air:free', 'baidu/cobuddy:free', 'mistralai/mistral-nemo-12b-instruct:free', 'meta-llama/llama-3.3-70b-instruct:free', 'meta-llama/llama-3.1-8b-instruct:free', 'huggingfaceh4/zephyr-7b-beta:free', 'nousresearch/hermes-3-llama-3.1-405b:free'],
    website: 'https://openrouter.ai',
    docsUrl: 'https://openrouter.ai/docs',
    pricingUrl: 'https://openrouter.ai/models',
  },
  {
    id: 'pollinations',
    name: 'Pollinations',
    description: 'Pollinations free tier. Anonymous access, no key required.',
    category: ['llm'],
    baseUrl: 'https://text.pollinations.ai/openai',
    envKey: '',
    models: ['openai-fast'],
    freeModels: ['openai-fast'],
    website: 'https://pollinations.ai',
    docsUrl: 'https://pollinations.ai/docs',
    pricingUrl: '',
  },
  {
    id: 'llm7',
    name: 'LLM7',
    description: 'LLM7 free API. Multiple open-source models.',
    category: ['llm'],
    baseUrl: 'https://api.llm7.io/v1',
    envKey: 'LLM7_API_KEY',
    models: ['openai/gpt-oss-20b', 'meta-llama/Llama-3.1-8B-Turbo', 'mistralai/Codestral-2501', 'THUDM/glm-4.6V-flash'],
    freeModels: ['openai/gpt-oss-20b', 'meta-llama/Llama-3.1-8B-Turbo', 'mistralai/Codestral-2501', 'THUDM/glm-4.6V-flash'],
    website: 'https://llm7.io',
    docsUrl: 'https://docs.llm7.io',
    pricingUrl: '',
  },
  {
    id: 'kilo-gateway',
    name: 'Kilo Gateway',
    description: 'Kilo Gateway free tier. Nemotron 120B.',
    category: ['llm'],
    baseUrl: 'https://api.kilo.ai/v1',
    envKey: 'KILO_API_KEY',
    models: ['nvidia/llama-3.1-nemotron-super-120b-v1'],
    freeModels: ['nvidia/llama-3.1-nemotron-super-120b-v1'],
    website: 'https://kilo.ai',
    docsUrl: 'https://docs.kilo.ai',
    pricingUrl: '',
  },
  {
    id: 'ollama-cloud',
    name: 'Ollama Cloud',
    description: 'Ollama Cloud free tier. Large open-source models.',
    category: ['llm'],
    baseUrl: 'https://ollama.com/v1',
    envKey: 'OLLAMA_CLOUD_API_KEY',
    models: ['gpt-oss:120b', 'kimi-k2.6', 'deepseek-v4-flash', 'glm-5.2', 'qwen3-coder:480b', 'devstral-2:123b'],
    freeModels: ['gpt-oss:120b', 'kimi-k2.6', 'deepseek-v4-flash', 'glm-5.2', 'qwen3-coder:480b', 'devstral-2:123b'],
    website: 'https://ollama.com',
    docsUrl: 'https://ollama.com/api',
    pricingUrl: '',
  },
  {
    id: 'moonshot',
    name: 'Moonshot (Kimi)',
    description: 'Kimi models. Good for orchestration and long context.',
    category: ['llm'],
    baseUrl: 'https://api.moonshot.cn/v1',
    envKey: 'MOONSHOT_API_KEY',
    models: ['moonshot-v1-128k', 'moonshot-v1-32k', 'moonshot-v1-8k', 'moonshot-v1-128k-vision-preview'],
    freeModels: [],
    website: 'https://platform.moonshot.cn',
    docsUrl: 'https://platform.moonshot.cn/docs',
    pricingUrl: 'https://platform.moonshot.cn/pricing',
  },
  {
    id: 'xiaomi',
    name: 'Xiaomi (MiMo)',
    description: 'MiMo models. Strong at database and structured data.',
    category: ['llm'],
    baseUrl: 'https://api.xiaomi.com/v1',
    envKey: 'XIAOMI_API_KEY',
    models: ['MiMo-7B-RL', 'doubao-seed-1.6', 'doubao-1.5-pro-256k'],
    freeModels: [],
    website: 'https://dev.mi.com',
    docsUrl: 'https://dev.mi.com/ai',
    pricingUrl: '',
  },
  {
    id: 'pika',
    name: 'Pika Labs',
    description: 'AI video generation and editing.',
    category: ['video'],
    baseUrl: 'https://api.pika.art/v1',
    envKey: 'PIKA_API_KEY',
    models: ['pika-1.0', 'pika-2.0'],
    freeModels: [],
    website: 'https://pika.art',
    docsUrl: 'https://pika.art/docs',
    pricingUrl: 'https://pika.art/pricing',
  },
  {
    id: 'localai',
    name: 'LocalAI',
    description: 'Unified local API. OpenAI-compatible. Multi-model.',
    category: ['llm'],
    baseUrl: 'http://localhost:8080/v1',
    envKey: 'LOCALAI_BASE_URL',
    models: ['any-loaded-model'],
    freeModels: ['any-loaded-model'],
    website: 'https://localai.io',
    docsUrl: 'https://localai.io/basics',
    pricingUrl: '',
  },
  {
    id: 'leonardo',
    name: 'Leonardo AI',
    description: 'AI image generation with fine-grained control.',
    category: ['image'],
    baseUrl: 'https://cloud.leonardo.ai/api/rest/v1',
    envKey: 'LEONARDO_API_KEY',
    models: ['leonardo-1.0', 'alchemy-1.0'],
    freeModels: [],
    website: 'https://leonardo.ai',
    docsUrl: 'https://docs.leonardo.ai',
    pricingUrl: 'https://leonardo.ai/pricing',
  },

  // === Additional free-tier providers ===
  {
    id: 'siliconflow',
    name: 'SiliconFlow',
    description: 'SiliconFlow 200+ models, free tier. DeepSeek V4, Qwen3, GLM, Kimi.',
    category: ['llm'],
    baseUrl: 'https://api.siliconflow.cn/v1',
    envKey: 'SILICONFLOW_API_KEY',
    models: ['deepseek-ai/DeepSeek-V4-Flash', 'Qwen/Qwen3-32B', 'zai-org/GLM-4.5-Air', 'moonshotai/Kimi-K2.5', 'meta-llama/Meta-Llama-3.1-8B-Instruct', 'MiniMaxAI/MiniMax-M2.5'],
    freeModels: ['deepseek-ai/DeepSeek-V4-Flash', 'Qwen/Qwen3-32B', 'zai-org/GLM-4.5-Air', 'moonshotai/Kimi-K2.5', 'meta-llama/Meta-Llama-3.1-8B-Instruct', 'MiniMaxAI/MiniMax-M2.5'],
    website: 'https://siliconflow.com',
    docsUrl: 'https://docs.siliconflow.com',
    pricingUrl: 'https://siliconflow.com/pricing',
  },
  {
    id: 'kluster',
    name: 'Kluster AI',
    description: 'Kluster AI free DeepSeek R1, Llama 4, Qwen3. High-throughput inference.',
    category: ['llm'],
    baseUrl: 'https://api.kluster.ai/v1',
    envKey: 'KLUSTER_API_KEY',
    models: ['deepseek-ai/DeepSeek-R1-0528', 'deepseek-ai/DeepSeek-V3-0324', 'meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8', 'meta-llama/Llama-4-Scout-17B-16E-Instruct', 'google/gemma-3-27b-it'],
    freeModels: ['deepseek-ai/DeepSeek-R1-0528', 'deepseek-ai/DeepSeek-V3-0324', 'meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8', 'meta-llama/Llama-4-Scout-17B-16E-Instruct', 'google/gemma-3-27b-it'],
    website: 'https://kluster.ai',
    docsUrl: 'https://docs.kluster.ai',
    pricingUrl: 'https://kluster.ai/pricing',
  },
  {
    id: 'nous-portal',
    name: 'Nous Portal',
    description: 'Nous Portal subscription gateway. 300+ models via OpenRouter. Hermes 4 native. Free tier available.',
    category: ['llm'],
    baseUrl: 'https://inference-api.nousresearch.com/v1',
    envKey: 'NOUS_PORTAL_API_KEY',
    models: ['NousResearch/Hermes-4-70B', 'NousResearch/Hermes-4-405B', 'anthropic/claude-sonnet-4.6', 'google/gemini-2.5-pro', 'deepseek/deepseek-v4-pro', 'qwen/qwen3.7-max'],
    freeModels: ['NousResearch/Hermes-4-70B', 'NousResearch/Hermes-4-405B'],
    website: 'https://portal.nousresearch.com',
    docsUrl: 'https://hermes-agent.nousresearch.com/docs/integrations/nous-portal',
    pricingUrl: 'https://portal.nousresearch.com/manage-subscription',
  },
];

/**
 * Get a provider by ID
 */
export function getProvider(id: string): ProviderEntry | undefined {
  return PROVIDER_CATALOG.find((p) => p.id === id);
}

/**
 * Get all provider IDs
 */
export function getAllProviderIds(): string[] {
  return PROVIDER_CATALOG.map((p) => p.id);
}

/**
 * Get providers by category
 */
export function getProvidersByCategory(category: ProviderCategory): ProviderEntry[] {
  return PROVIDER_CATALOG.filter((p) => p.category.includes(category));
}

/**
 * Search providers by name or description
 */
export function searchProviders(query: string): ProviderEntry[] {
  const lower = query.toLowerCase();
  return PROVIDER_CATALOG.filter(
    (p) =>
      p.id.includes(lower) ||
      p.name.toLowerCase().includes(lower) ||
      p.description.toLowerCase().includes(lower)
  );
}
