/**
 * DMR-X Configuration Manager
 *
 * Manages .dmrx/ directory, config.json, and .env file.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync, appendFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

export interface DMRXConfig {
  version: string;
  project: {
    name: string;
    created: string;
  };
  providers: RegisteredProvider[];
  defaults: {
    llm: string | null;
    image: string | null;
    embedding: string | null;
    audio_tts: string | null;
    audio_stt: string | null;
    video: string | null;
    music: string | null;
  };
  settings: {
    maxRetries: number;
    timeoutMs: number;
    logLevel: string;
  };
}

export interface RegisteredProvider {
  id: string;
  name: string;
  enabled: boolean;
  addedAt: string;
  models: string[];
  isLocal: boolean;
}

const DMRX_DIR = '.dmrx';
const CONFIG_FILE = 'config.json';
const ENV_FILE = '.env';
const DOCKER_COMPOSE_FILE = 'docker-compose.yml';

export function getDMRXDir(cwd: string = process.cwd()): string {
  return join(cwd, DMRX_DIR);
}

export function getConfigPath(cwd: string = process.cwd()): string {
  return join(getDMRXDir(cwd), CONFIG_FILE);
}

export function getEnvPath(cwd: string = process.cwd()): string {
  return join(cwd, ENV_FILE);
}

export function getDockerComposePath(cwd: string = process.cwd()): string {
  return join(cwd, DOCKER_COMPOSE_FILE);
}

export function isInitialized(cwd: string = process.cwd()): boolean {
  return existsSync(getDMRXDir(cwd)) && existsSync(getConfigPath(cwd));
}

export function createDefaultConfig(projectName: string): DMRXConfig {
  return {
    version: '0.1.0',
    project: {
      name: projectName,
      created: new Date().toISOString(),
    },
    providers: [],
    defaults: {
      llm: null,
      image: null,
      embedding: null,
      audio_tts: null,
      audio_stt: null,
      video: null,
      music: null,
    },
    settings: {
      maxRetries: 3,
      timeoutMs: 30000,
      logLevel: 'info',
    },
  };
}

export function loadConfig(cwd: string = process.cwd()): DMRXConfig {
  const configPath = getConfigPath(cwd);
  if (!existsSync(configPath)) {
    throw new Error('DMR-X not initialized. Run "dmrx init" first.');
  }
  const raw = readFileSync(configPath, 'utf-8');
  return JSON.parse(raw) as DMRXConfig;
}

export function saveConfig(config: DMRXConfig, cwd: string = process.cwd()): void {
  const configPath = getConfigPath(cwd);
  writeFileSync(configPath, JSON.stringify(config, null, 2) + '\n', 'utf-8');
}

export function ensureEnvFile(cwd: string = process.cwd()): string {
  const envPath = getEnvPath(cwd);
  if (!existsSync(envPath)) {
    writeFileSync(envPath, '# DMR-X Environment Variables\n# Provider API Keys\n\n', 'utf-8');
  }
  return envPath;
}

export function setEnvVar(key: string, value: string, cwd: string = process.cwd()): void {
  const envPath = ensureEnvFile(cwd);
  const content = readFileSync(envPath, 'utf-8');

  // Check if key already exists
  const regex = new RegExp(`^${key}=.*$`, 'm');
  if (regex.test(content)) {
    // Replace existing key
    const updated = content.replace(regex, `${key}=${value}`);
    writeFileSync(envPath, updated, 'utf-8');
  } else {
    // Append new key
    appendFileSync(envPath, `${key}=${value}\n`, 'utf-8');
  }
}

export function getEnvVar(key: string, cwd: string = process.cwd()): string | undefined {
  const envPath = getEnvPath(cwd);
  if (!existsSync(envPath)) return undefined;

  const content = readFileSync(envPath, 'utf-8');
  const regex = new RegExp(`^${key}=(.*)$`, 'm');
  const match = content.match(regex);
  return match ? match[1] : undefined;
}

export function initProject(projectName: string, cwd: string = process.cwd()): void {
  const dmrxDir = getDMRXDir(cwd);

  // Create .dmrx directory
  if (!existsSync(dmrxDir)) {
    mkdirSync(dmrxDir, { recursive: true });
  }

  // Create config
  const config = createDefaultConfig(projectName);
  saveConfig(config, cwd);

  // Create .env file
  ensureEnvFile(cwd);
}

export function createDockerCompose(cwd: string = process.cwd()): void {
  const dockerComposeContent = `# DMR-X Infrastructure
# Generated by dmrx init

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: dmr-x-postgres
    environment:
      POSTGRES_USER: dmrx
      POSTGRES_PASSWORD: dmrx
      POSTGRES_DB: dmr_x
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dmrx -d dmr_x"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: dmr-x-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
`;

  writeFileSync(getDockerComposePath(cwd), dockerComposeContent, 'utf-8');
}
