#!/usr/bin/env bun
/**
 * Regenerate `packages/core/src/mcp-catalog.ts` from the hand-maintained
 * manifest + the vendored fork of modelcontextprotocol/servers.
 *
 * Usage:
 *   bun scripts/generate-mcp-catalog.ts            # write the generated file
 *   bun scripts/generate-mcp-catalog.ts --check    # exit 1 if the file is stale
 *
 * Environment:
 *   DMRX_MCP_SERVERS_DIR   path to the vendored fork (default vendored/servers).
 *                          Tests point this at a fixture directory.
 *
 * Merge rules:
 * - `source: 'fork'` entries are enriched from the fork: package name and
 *   description (package.json for TypeScript servers, pyproject.toml for
 *   Python ones), plus a docs URL into the upstream repo. `command`/`args`
 *   come from the manifest — the fork's packaging does not encode how the
 *   server is invoked (npx vs uvx).
 * - `source: 'curated'` entries pass through verbatim (they have no fork dir).
 *
 * Validation (fails the build):
 * - every `{{TOKEN}}` in args must be declared in `requiredEnv`
 * - stdio entries need `command`; sse/http entries need `url`
 * - ids unique; fork entries resolve to a real directory in the fork
 *
 * The emitted file is self-contained: it re-declares the public types and
 * helpers so consumers (`@dmr-x/core` re-export, gateway route, UI) never see
 * the manifest.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { MCP_CATALOG_MANIFEST } from '../packages/core/src/mcp-catalog.manifest.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..');
const SERVERS_DIR =
  process.env.DMRX_MCP_SERVERS_DIR || join(REPO_ROOT, 'vendored', 'servers');
const OUT_FILE = join(REPO_ROOT, 'packages', 'core', 'src', 'mcp-catalog.ts');

const isCheck = process.argv.includes('--check');

// ── Fork readers ────────────────────────────────────────────────────────────

function readPackageJson(dir: string) {
  const p = join(dir, 'package.json');
  if (!existsSync(p)) return null;
  return JSON.parse(readFileSync(p, 'utf-8'));
}

function readPyProject(dir: string) {
  const p = join(dir, 'pyproject.toml');
  if (!existsSync(p)) return null;
  const raw = readFileSync(p, 'utf-8');
  const name = /^name\s*=\s*"([^"]+)"/m.exec(raw)?.[1];
  const description = /^description\s*=\s*"([^"]+)"/m.exec(raw)?.[1];
  if (!name) return null;
  return { name, description };
}

function forkServerInfo(id: string, forkDir?: string): { name: string; description: string } | null {
  const dir = join(SERVERS_DIR, 'src', forkDir ?? id);
  if (!existsSync(dir)) return null;

  const ts = readPackageJson(dir);
  if (ts) return { name: ts.name, description: ts.description ?? '' };

  const py = readPyProject(dir);
  if (py) return { name: py.name, description: py.description ?? '' };

  throw new Error(
    `Fork server '${id}' at ${dir} has neither package.json nor pyproject.toml — cannot enrich.`,
  );
}

// ── Emitter ─────────────────────────────────────────────────────────────────

/** Deterministic TS object-literal printer for the flat catalog entries. */
function entryLiteral(entry: Record<string, unknown>): string {
  const lines: string[] = [];
  for (const [key, value] of Object.entries(entry)) {
    if (value === undefined) continue;
    if (Array.isArray(value)) {
      const isObjArray = value.length > 0 && typeof value[0] === 'object' && value[0] !== null;
      if (isObjArray) {
        const inner = (value as Array<Record<string, unknown>>)
          .map((o) => {
            const fields = Object.entries(o)
              .filter(([, v]) => v !== undefined)
              .map(([k, v]) => `${k}: ${JSON.stringify(v)}`);
            return `      { ${fields.join(', ')} },`;
          })
          .join('\n');
        lines.push(`    ${key}: [\n${inner}\n    ],`);
      } else {
        lines.push(`    ${key}: [${value.map((v) => JSON.stringify(v)).join(', ')}],`);
      }
    } else if (typeof value === 'object' && value !== null) {
      lines.push(`    ${key}: ${JSON.stringify(value)},`);
    } else {
      lines.push(`    ${key}: ${JSON.stringify(value)},`);
    }
  }
  return lines.join('\n');
}

const TEMPLATE = `/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Generated by \`bun run mcp:catalog:gen\` (scripts/generate-mcp-catalog.ts)
 * from:
 *   - packages/core/src/mcp-catalog.manifest.ts  (curated metadata)
 *   - vendored/servers                           (fork of modelcontextprotocol/servers)
 *
 * To add or change a server, edit the manifest and regenerate. Run
 * \`bun run mcp:catalog:check\` in CI to fail on drift.
 */

export type McpCatalogCategory =
  | 'development'
  | 'data'
  | 'productivity'
  | 'search'
  | 'cloud'
  | 'automation'
  | 'memory';

export interface McpCatalogEnvVar {
  /** Environment variable name, also the \`{{token}}\` used in \`args\`. */
  key: string;
  /** Human label for the generated form field. */
  label: string;
  /** Rendered under the field. Say where to obtain the value. */
  help?: string;
  /** Render as a password field and never echo the value back to the client. */
  secret?: boolean;
  /** A field may be optional — the server still starts without it. */
  optional?: boolean;
  /** Prefilled default for non-secret fields. */
  placeholder?: string;
}

export interface McpCatalogEntry {
  id: string;
  name: string;
  description: string;
  category: McpCatalogCategory;
  /** lucide-react icon name, resolved by the UI. */
  icon: string;
  transport: 'stdio' | 'sse' | 'http';
  command?: string;
  args?: string[];
  url?: string;
  requiredEnv: McpCatalogEnvVar[];
  docsUrl?: string;
  /** Official reference implementation vs. third-party. Shown as a badge. */
  official?: boolean;
}

export const MCP_CATALOG: readonly McpCatalogEntry[] = [
{{ENTRIES}}
];

export const MCP_CATALOG_CATEGORIES: Record<McpCatalogCategory, string> = {
  development: 'Development',
  data: 'Data',
  productivity: 'Productivity',
  search: 'Search & Web',
  cloud: 'Cloud & Infra',
  automation: 'Automation',
  memory: 'Memory & Reasoning',
};

export function getCatalogEntry(id: string): McpCatalogEntry | undefined {
  return MCP_CATALOG.find((e) => e.id === id);
}

/**
 * Substitute \`{{KEY}}\` tokens in a catalog entry's args from supplied values.
 *
 * Some servers take a path or connection string as a positional argument
 * rather than an env var (filesystem, postgres, sqlite), so the same value the
 * operator typed has to be able to reach either place. A token with no
 * matching value is left intact so the failure surfaces in the connection test
 * rather than silently becoming the empty string — an empty allowlist path
 * would otherwise read as "current directory".
 */
export function renderCatalogArgs(args: string[] | undefined, values: Record<string, string>): string[] {
  if (!args) return [];
  return args.map((arg) =>
    arg.replace(/\\{\\{(\\w+)\\}\\}/g, (whole, key: string) =>
      values[key] !== undefined && values[key] !== '' ? values[key] : whole,
    ),
  );
}
`.trim() + '\n';

// ── Build the enriched entries ───────────────────────────────────────────────

function buildEntries(): Array<Record<string, unknown>> {
  const seen = new Set<string>();
  const resolvedForkDirs = new Set<string>();
  const entries: Array<Record<string, unknown>> = [];
  for (const m of MCP_CATALOG_MANIFEST) {
    if (seen.has(m.id)) throw new Error(`Duplicate catalog id: ${m.id}`);
    seen.add(m.id);

    const out: Record<string, unknown> = {
      id: m.id,
      name: m.name,
      category: m.category,
      icon: m.icon,
      transport: m.transport,
      requiredEnv: m.requiredEnv,
    };

    if (m.source === 'fork') {
      const info = forkServerInfo(m.id, m.forkDir);
      if (!info) {
        throw new Error(
          `Catalog entry '${m.id}' is marked source:'fork' but no directory ` +
            `src/${m.forkDir ?? m.id} exists in ${SERVERS_DIR}. Either add it to the fork ` +
            `(git -C vendored/servers pull) or change the entry to source:'curated'.`,
        );
      }
      out.name = m.name;
      out.description = info.description;
      out.docsUrl = `https://github.com/modelcontextprotocol/servers/tree/main/src/${m.forkDir ?? m.id}`;
      resolvedForkDirs.add(m.forkDir ?? m.id);
    } else {
      if (!m.description) {
        // curated entries carry their own description inline in the manifest
        throw new Error(`Curated entry '${m.id}' must provide a description`);
      }
      out.description = m.description;
      if (m.docsUrl) out.docsUrl = m.docsUrl;
    }

    if (m.command) out.command = m.command;
    if (m.args) out.args = m.args;
    if (m.url) out.url = m.url;
    if (m.official !== undefined) out.official = m.official;

    // Validate transport contract.
    if (m.transport === 'stdio' && !m.command) {
      throw new Error(`Entry '${m.id}' is stdio but has no command`);
    }
    if (m.transport !== 'stdio' && !m.url) {
      throw new Error(`Entry '${m.id}' is ${m.transport} but has no url`);
    }

    // Validate {{TOKEN}}s are declared.
    const tokens = (m.args ?? []).flatMap((a) =>
      [...a.matchAll(/\{\{(\w+)\}\}/g)].map((x) => x[1]),
    );
    const declared = new Set(m.requiredEnv.map((v) => v.key));
    for (const t of tokens) {
      if (!declared.has(t)) {
        throw new Error(`Entry '${m.id}' uses {{${t}}} but does not declare it in requiredEnv`);
      }
    }

    entries.push(out);
  }

  // Warn (not fail) when the fork carries servers nobody has categorized yet —
  // upstream adds new reference servers over time.
  if (existsSync(join(SERVERS_DIR, 'src'))) {
    for (const dir of readdirSync(join(SERVERS_DIR, 'src'))) {
      const full = join(SERVERS_DIR, 'src', dir);
      if (!existsSync(join(full, 'package.json')) && !existsSync(join(full, 'pyproject.toml'))) {
        continue; // not a server package
      }
      if (!seen.has(dir) && !resolvedForkDirs.has(dir)) {
        console.warn(
          `[mcp-catalog:gen] fork has unlisted server '${dir}' — add a manifest entry to surface it in the UI`,
        );
      }
    }
  }

  return entries;
}

// ── Main ────────────────────────────────────────────────────────────────────

/** Render the complete generated file from the manifest + fork. Exported for tests. */
export function render(): string {
  const entries = buildEntries();
  const literal = entries
    .map((e) => `  {\n${entryLiteral(e)}\n  },`)
    .join('\n');
  return TEMPLATE.replace('{{ENTRIES}}', literal);
}

/** Build the enriched entries. Exported for tests (points at SERVERS_DIR). */
export function buildEntriesForTest(): Array<Record<string, unknown>> {
  return buildEntries();
}

// Run as a script (`bun scripts/generate-mcp-catalog.ts [--check]`) — the
// exports above are for unit tests importing this module.
if (import.meta.main) {
  const generated = render();

  if (isCheck) {
    const current = existsSync(OUT_FILE) ? readFileSync(OUT_FILE, 'utf-8') : '';
    if (current === generated) {
      console.info('[mcp-catalog:check] up to date');
      process.exit(0);
    }
    console.error(
      '[mcp-catalog:check] mcp-catalog.ts is stale. Run `bun run mcp:catalog:gen` and commit the result.',
    );
    process.exit(1);
  }

  writeFileSync(OUT_FILE, generated, 'utf-8');
  console.info(`[mcp-catalog:gen] wrote ${OUT_FILE} (${MCP_CATALOG_MANIFEST.length} entries)`);
}
