package dmrx

import "encoding/json"

// ── Modality ─────────────────────────────────────────────────────

// Modality represents the AI modality — what kind of content the model processes.
type Modality string

const (
	ModalityLLM             Modality = "llm"
	ModalityDiffusion       Modality = "diffusion"
	ModalityEmbedding       Modality = "embedding"
	ModalityAudioTTS        Modality = "audio_tts"
	ModalityAudioSTT        Modality = "audio_stt"
	ModalityAudioSeparation Modality = "audio_separation"
	ModalityVideo           Modality = "video"
	ModalityVideoAnalysis   Modality = "video_analysis"
	ModalityMusic           Modality = "music"
	ModalityReranking       Modality = "reranking"
	ModalityModeration      Modality = "moderation"
	ModalityCodeCompletion  Modality = "code_completion"
	ModalityOCR             Modality = "ocr"
	ModalityImageUpscaling  Modality = "image_upscaling"
	ModalityImageInpainting Modality = "image_inpainting"
	ModalityVision          Modality = "vision"
	Modality3D              Modality = "3d"
)

// QualityTarget controls the provider routing strategy.
type QualityTarget string

const (
	QualityFrontier QualityTarget = "frontier"
	QualityBalanced QualityTarget = "balanced"
	QualityEconomy  QualityTarget = "economy"
)

// ── Token Usage ──────────────────────────────────────────────────

// TokenUsage represents token usage statistics.
type TokenUsage struct {
	PromptTokens     int `json:"prompt_tokens"`
	CompletionTokens int `json:"completion_tokens"`
	TotalTokens      int `json:"total_tokens"`
}

// ── Messages ─────────────────────────────────────────────────────

// MessageRole represents the role of a message participant.
type MessageRole string

const (
	RoleSystem    MessageRole = "system"
	RoleUser      MessageRole = "user"
	RoleAssistant MessageRole = "assistant"
	RoleTool      MessageRole = "tool"
)

// ContentPart represents a piece of message content (text, image, or audio).
type ContentPart struct {
	Type       string           `json:"type"`
	Text       string           `json:"text,omitempty"`
	ImageURL   *ImageURLContent `json:"image_url,omitempty"`
	InputAudio *AudioContent    `json:"input_audio,omitempty"`
}

// ImageURLContent represents an image URL reference in a message.
type ImageURLContent struct {
	URL    string `json:"url"`
	Detail string `json:"detail,omitempty"` // auto, low, high
}

// AudioContent represents inline audio data in a message.
type AudioContent struct {
	Data   string `json:"data"`
	Format string `json:"format"` // wav, mp3
}

// ToolCall represents a function call generated by the model.
type ToolCall struct {
	ID       string        `json:"id"`
	Type     string        `json:"type"` // "function"
	Function ToolCallFunc  `json:"function"`
}

// ToolCallFunc represents the function details in a tool call.
type ToolCallFunc struct {
	Name      string `json:"name"`
	Arguments string `json:"arguments"` // JSON string
}

// Message represents a chat message in the conversation.
type Message struct {
	Role       MessageRole  `json:"role"`
	Content    interface{}  `json:"content,omitempty"` // string or []ContentPart
	Name       string       `json:"name,omitempty"`
	ToolCalls  []ToolCall   `json:"tool_calls,omitempty"`
	ToolCallID string       `json:"tool_call_id,omitempty"`
}

// Tool represents a tool/function definition available to the model.
type Tool struct {
	Type     string         `json:"type"` // "function"
	Function ToolDefinition `json:"function"`
}

// ToolDefinition represents the definition of a callable function.
type ToolDefinition struct {
	Name        string          `json:"name"`
	Description string          `json:"description,omitempty"`
	Parameters  json.RawMessage `json:"parameters,omitempty"`
}

// ── Chat Completion Request / Response ───────────────────────────

// ChatCompletionRequest is the request body for POST /v1/chat/completions.
type ChatCompletionRequest struct {
	Model               string              `json:"model"`
	Messages            []Message           `json:"messages"`
	Temperature         *float64            `json:"temperature,omitempty"`
	MaxTokens           *int                `json:"max_tokens,omitempty"`
	TopP                *float64            `json:"top_p,omitempty"`
	FrequencyPenalty    *float64            `json:"frequency_penalty,omitempty"`
	PresencePenalty     *float64            `json:"presence_penalty,omitempty"`
	Stop                interface{}         `json:"stop,omitempty"` // string or []string
	Stream              bool                `json:"stream"`
	Tools               []Tool              `json:"tools,omitempty"`
	ToolChoice          interface{}         `json:"tool_choice,omitempty"`
	ResponseFormat      *ResponseFormat     `json:"response_format,omitempty"`
	Seed                *int                `json:"seed,omitempty"`
	N                   *int                `json:"n,omitempty"`
	User                string              `json:"user,omitempty"`

	// DMR-X specific routing parameters
	Quality            QualityTarget `json:"quality,omitempty"`
	ProviderPreference []string      `json:"provider_preference,omitempty"`
	ProviderBlacklist  []string      `json:"provider_blacklist,omitempty"`
	LatencyTarget      interface{}   `json:"latency_target,omitempty"` // int or string
	CostTarget         interface{}   `json:"cost_target,omitempty"`   // float or string
	LocalFirst         *bool         `json:"local_first,omitempty"`
	RequirePrivacy     *bool         `json:"require_privacy,omitempty"`
}

// ResponseFormat specifies the format of the model's response.
type ResponseFormat struct {
	Type string `json:"type"` // "text" or "json_object"
}

// ChatCompletionResponse is the response from POST /v1/chat/completions.
type ChatCompletionResponse struct {
	ID        string                 `json:"id"`
	Object    string                 `json:"object"` // "chat.completion"
	Created   int64                  `json:"created"`
	Model     string                 `json:"model"`
	Choices   []ChatCompletionChoice `json:"choices"`
	Usage     *TokenUsage            `json:"usage,omitempty"`
	Provider  string                 `json:"provider,omitempty"`
	LatencyMs float64                `json:"latency_ms,omitempty"`
}

// ChatCompletionChoice represents a single completion choice.
type ChatCompletionChoice struct {
	Index        int             `json:"index"`
	Message      Message         `json:"message"`
	FinishReason string          `json:"finish_reason,omitempty"`
}

// ── Embedding Request / Response ─────────────────────────────────

// EmbeddingRequest is the request body for POST /v1/embeddings.
type EmbeddingRequest struct {
	Model    string   `json:"model"`
	Input    []string `json:"input"`
	Dimensions *int   `json:"dimensions,omitempty"`
	EncodingFormat string `json:"encoding_format,omitempty"` // "float" or "base64"
	User     string   `json:"user,omitempty"`
}

// EmbeddingResponse is the response from POST /v1/embeddings.
type EmbeddingResponse struct {
	Object string          `json:"object"` // "list"
	Data   []EmbeddingData `json:"data"`
	Model  string          `json:"model"`
	Usage  EmbeddingUsage  `json:"usage"`
}

// EmbeddingData represents a single embedding vector.
type EmbeddingData struct {
	Index     int       `json:"index"`
	Embedding []float64 `json:"embedding"`
	Object    string    `json:"object"` // "embedding"
}

// EmbeddingUsage represents token usage for an embedding request.
type EmbeddingUsage struct {
	PromptTokens int `json:"prompt_tokens"`
	TotalTokens  int `json:"total_tokens"`
}

// ── Image Generation Request / Response ──────────────────────────

// ImageGenerationRequest is the request body for POST /v1/images/generations.
type ImageGenerationRequest struct {
	Model           string   `json:"model"`
	Prompt          string   `json:"prompt"`
	NegativePrompt  string   `json:"negative_prompt,omitempty"`
	N               *int     `json:"n,omitempty"`
	Size            string   `json:"size,omitempty"`
	Width           *int     `json:"width,omitempty"`
	Height          *int     `json:"height,omitempty"`
	Steps           *int     `json:"steps,omitempty"`
	Style           string   `json:"style,omitempty"`
	Quality         string   `json:"quality,omitempty"`
	ResponseFormat  string   `json:"response_format,omitempty"` // "url" or "b64_json"
}

// ImageGenerationResponse is the response from POST /v1/images/generations.
type ImageGenerationResponse struct {
	Created int64            `json:"created"`
	Data    []GeneratedImage `json:"data"`
}

// GeneratedImage represents a generated image.
type GeneratedImage struct {
	URL           string `json:"url,omitempty"`
	B64JSON       string `json:"b64_json,omitempty"`
	RevisedPrompt string `json:"revised_prompt,omitempty"`
}

// ── Audio Request / Response ─────────────────────────────────────

// AudioSpeechRequest is the request body for POST /v1/audio/speech (TTS).
type AudioSpeechRequest struct {
	Model           string  `json:"model"`
	Input           string  `json:"input"`
	Voice           string  `json:"voice"`
	Speed           *float64 `json:"speed,omitempty"`
	ResponseFormat  string  `json:"response_format,omitempty"` // mp3, opus, aac, flac, wav
	Language        string  `json:"language,omitempty"`
}

// AudioSpeechResponse is the response from POST /v1/audio/speech.
type AudioSpeechResponse struct {
	ContentType string `json:"-"`
	Data        []byte `json:"-"`
}

// AudioTranscriptionRequest is the request body for POST /v1/audio/transcriptions (STT).
type AudioTranscriptionRequest struct {
	Model          string  `json:"model"`
	Audio          string  `json:"audio"` // base64-encoded
	AudioFormat    string  `json:"audio_format,omitempty"` // wav, mp3, m4a, webm
	Language       string  `json:"language,omitempty"`
	Prompt         string  `json:"prompt,omitempty"`
	ResponseFormat string  `json:"response_format,omitempty"` // json, text, srt, vtt, verbose_json
	Temperature    *float64 `json:"temperature,omitempty"`
}

// AudioTranscriptionResponse is the response from POST /v1/audio/transcriptions.
type AudioTranscriptionResponse struct {
	Text     string                 `json:"text"`
	Segments []TranscriptionSegment `json:"segments,omitempty"`
	Language string                 `json:"language,omitempty"`
	Duration float64                `json:"duration,omitempty"`
}

// TranscriptionSegment represents a segment of a transcription.
type TranscriptionSegment struct {
	ID              int     `json:"id"`
	Seek            int     `json:"seek"`
	Start           float64 `json:"start"`
	End             float64 `json:"end"`
	Text            string  `json:"text"`
	Tokens          []int   `json:"tokens"`
	Temperature     float64 `json:"temperature"`
	AvgLogprob      float64 `json:"avg_logprob"`
	CompressionRatio float64 `json:"compression_ratio"`
	NoSpeechProb    float64 `json:"no_speech_prob"`
}

// ── Video Generation Request / Response ──────────────────────────

// VideoGenerationRequest is the request body for POST /v1/video/generations.
type VideoGenerationRequest struct {
	Model            string        `json:"model"`
	Prompt           string        `json:"prompt"`
	NegativePrompt   string        `json:"negative_prompt,omitempty"`
	Duration         *int          `json:"duration,omitempty"`
	FPS              *int          `json:"fps,omitempty"`
	AspectRatio      string        `json:"aspect_ratio,omitempty"`
	Resolution       string        `json:"resolution,omitempty"`
	GenerateAudio    *bool         `json:"generate_audio,omitempty"`
	CameraFixed      *bool         `json:"camera_fixed,omitempty"`
	CameraControl    *CameraControl `json:"camera_control,omitempty"`
	ReferenceImages  []string      `json:"reference_images,omitempty"`
	ReferenceVideo   string        `json:"reference_video,omitempty"`
	EditVideo        string        `json:"edit_video,omitempty"`
	EditInstruction  string        `json:"edit_instruction,omitempty"`
	ExtendVideo      string        `json:"extend_video,omitempty"`
}

// CameraControl represents camera movement for video generation.
type CameraControl struct {
	Type      string `json:"type"` // pan, tilt, zoom, dolly, crane, tracking, orbital
	Direction string `json:"direction,omitempty"`
	Speed     string `json:"speed,omitempty"` // slow, medium, fast
}

// VideoGenerationResponse is the response from POST /v1/video/generations.
type VideoGenerationResponse struct {
	Created int64            `json:"created"`
	Data    []GeneratedVideo `json:"data"`
}

// GeneratedVideo represents a generated video.
type GeneratedVideo struct {
	URL        string  `json:"url,omitempty"`
	B64JSON    string  `json:"b64_json,omitempty"`
	Duration   float64 `json:"duration,omitempty"`
	FPS        int     `json:"fps,omitempty"`
	Resolution string  `json:"resolution,omitempty"`
	AudioURL   string  `json:"audio_url,omitempty"`
	HasAudio   bool    `json:"has_audio,omitempty"`
}

// ── Moderation Request / Response ──────────────────────────────────

// ModerationRequest is the request body for POST /v1/moderations.
type ModerationRequest struct {
	Model string `json:"model"`
	Input string `json:"input"`
}

// ModerationResponse is the response from POST /v1/moderations.
type ModerationResponse struct {
	ID      string             `json:"id"`
	Model   string             `json:"model"`
	Results []ModerationResult `json:"results"`
}

// ModerationResult represents the result of a moderation check.
type ModerationResult struct {
	Flagged        bool               `json:"flagged"`
	Categories     map[string]bool    `json:"categories"`
	CategoryScores map[string]float64 `json:"category_scores"`
}

// ── Rerank Request / Response ─────────────────────────────────────

// RerankRequest is the request body for POST /v1/rerank.
type RerankRequest struct {
	Model     string   `json:"model"`
	Query     string   `json:"query"`
	Documents []string `json:"documents"`
	TopN      *int     `json:"top_n,omitempty"`
}

// RerankResponse is the response from POST /v1/rerank.
type RerankResponse struct {
	ID      string         `json:"id"`
	Model   string         `json:"model"`
	Results []RerankResult `json:"results"`
}

// RerankResult represents a single reranking result.
type RerankResult struct {
	Index          int     `json:"index"`
	RelevanceScore float64 `json:"relevance_score"`
	Document       string  `json:"document,omitempty"`
}

// ── OCR Request / Response ────────────────────────────────────────

// OcrRequest is the request body for POST /v1/ocr.
type OcrRequest struct {
	Model           string `json:"model"`
	Image           string `json:"image"`
	Language        string `json:"language,omitempty"`
	DetectDirection *bool  `json:"detect_direction,omitempty"`
	Paragraph       *bool  `json:"paragraph,omitempty"`
	Lines           *bool  `json:"lines,omitempty"`
	Words           *bool  `json:"words,omitempty"`
}

// OcrResponse is the response from POST /v1/ocr.
type OcrResponse struct {
	Text                string    `json:"text"`
	OcrTexts            []OcrText `json:"ocr_texts,omitempty"`
	FullTextAnnotation  string    `json:"full_text_annotation,omitempty"`
}

// OcrText represents a single text element detected by OCR.
type OcrText struct {
	Text        string    `json:"text"`
	Confidence  *float64  `json:"confidence,omitempty"`
	BoundingBox []float64 `json:"bounding_box,omitempty"`
	Page        *int      `json:"page,omitempty"`
}

// ── Model List Request / Response ────────────────────────────────

// ModelList is the response from GET /v1/models.
type ModelList struct {
	Object string  `json:"object"` // "list"
	Data   []Model `json:"data"`
}

// Model represents an AI model available through DMR-X.
type Model struct {
	ID         string             `json:"id"`
	Object     string             `json:"object"` // "model"
	Created    int64              `json:"created"`
	OwnedBy    string             `json:"owned_by"`
	Permission []ModelPermission  `json:"permission"`
}

// ModelPermission represents permissions for a model.
type ModelPermission struct {
	ID                 string `json:"id"`
	Object             string `json:"object"` // "model_permission"
	Created            int64  `json:"created"`
	AllowCreateEngine  bool   `json:"allow_create_engine"`
	AllowSampling      bool   `json:"allow_sampling"`
	AllowLogprobs      bool   `json:"allow_logprobs"`
	AllowSearchIndices bool   `json:"allow_search_indices"`
	AllowView          bool   `json:"allow_view"`
	AllowFineTuning    bool   `json:"allow_fine_tuning"`
	Organization       string `json:"organization"`
}

// ── Stream Chunk Types ───────────────────────────────────────────

// StreamChunkType indicates the type of streaming chunk.
type StreamChunkType string

const (
	StreamChunkToken StreamChunkType = "token"
	StreamChunkDone  StreamChunkType = "done"
	StreamChunkError StreamChunkType = "error"
)

// StreamChunk is a single chunk from a streaming response.
type StreamChunk struct {
	Type  StreamChunkType `json:"type"`
	Data  json.RawMessage `json:"data"`
	Index int             `json:"index"`
}

// TokenData contains the content delta in a token stream chunk.
type TokenData struct {
	Content    *string     `json:"content,omitempty"`
	ToolCalls []ToolCall  `json:"tool_calls,omitempty"`
	Role      string      `json:"role,omitempty"`
}

// DoneData contains completion metadata.
type DoneData struct {
	RequestID    string     `json:"requestId"`
	ModelID      string     `json:"modelId"`
	FinishReason string     `json:"finishReason"`
	Usage        *TokenUsage `json:"usage,omitempty"`
}

// ErrorData contains error information in an error chunk.
type ErrorData struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}
