"""
Shared types used across all DMR-X API endpoints.
Mirrors packages/core/src/types/ from the DMR-X monorepo.
"""

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field


class Modality(str, Enum):
    """AI modality — what kind of content the model processes."""

    LLM = "llm"
    DIFFUSION = "diffusion"
    EMBEDDING = "embedding"
    AUDIO_TTS = "audio_tts"
    AUDIO_STT = "audio_stt"
    AUDIO_SEPARATION = "audio_separation"
    VIDEO = "video"
    VIDEO_ANALYSIS = "video_analysis"
    MUSIC = "music"
    RERANKING = "reranking"
    MODERATION = "moderation"
    CODE_COMPLETION = "code_completion"
    OCR = "ocr"
    IMAGE_UPSCALING = "image_upscaling"
    IMAGE_INPAINTING = "image_inpainting"
    VISION = "vision"
    THREE_D = "3d"


class QualityTarget(str, Enum):
    """Routing quality target — controls provider selection."""
    FRONTIER = "frontier"
    BALANCED = "balanced"
    ECONOMY = "economy"


class TokenUsage(BaseModel):
    """Token usage statistics for a request."""
    prompt_tokens: int = Field(..., description="Number of tokens in the prompt")
    completion_tokens: int = Field(..., description="Number of tokens in the completion")
    total_tokens: int = Field(..., description="Total tokens used")


class ContentPart(BaseModel):
    """A part of a message's content — text, image, or audio."""

    type: Literal["text", "image_url", "input_audio"] = Field(
        ..., description="Content part type"
    )
    text: Optional[str] = Field(None, description="Text content (for text type)")
    image_url: Optional[Dict[str, Any]] = Field(
        None, description="Image URL data (for image_url type)"
    )
    input_audio: Optional[Dict[str, Any]] = Field(
        None, description="Input audio data (for input_audio type)"
    )


class ToolCall(BaseModel):
    """A function call generated by the model."""

    id: str = Field(..., description="Tool call ID")
    type: Literal["function"] = Field("function", description="Tool call type")
    function: Dict[str, Any] = Field(
        ..., description="Function name and arguments"
    )


class Message(BaseModel):
    """A chat message in the conversation."""

    role: Literal["system", "user", "assistant", "tool"] = Field(
        ..., description="Message role"
    )
    content: Optional[Union[str, List[ContentPart]]] = Field(
        None, description="Message content"
    )
    name: Optional[str] = Field(None, description="Participant name")
    tool_calls: Optional[List[ToolCall]] = Field(
        None, description="Tool calls (assistant only)"
    )
    tool_call_id: Optional[str] = Field(
        None, description="Tool call ID being responded to (tool only)"
    )


class Tool(BaseModel):
    """A tool/function definition available to the model."""

    type: Literal["function"] = Field("function", description="Tool type")
    function: Dict[str, Any] = Field(
        ..., description="Function definition with name, description, parameters"
    )


# ── Stream Chunk Types ─────────────────────────────────────────────


class StreamChunk(BaseModel):
    """Base type for all streaming response chunks."""

    type: Literal["token", "done", "error", "image_partial", "video_partial", "audio_chunk", "audio_partial"] = Field(
        ..., description="Chunk type"
    )
    data: Any = Field(..., description="Chunk payload")
    index: int = Field(0, description="Chunk sequence index")


class TokenStreamChunk(StreamChunk):
    """A streaming token chunk from an LLM response."""

    type: Literal["token"] = "token"
    data: Dict[str, Any] = Field(
        ..., description="Token data with content and optional tool_calls"
    )


class DoneStreamChunk(StreamChunk):
    """Final chunk indicating the stream is complete."""

    type: Literal["done"] = "done"
    data: Dict[str, Any] = Field(
        ...,
        description="Done data with requestId, modelId, usage, and finishReason",
    )


class ErrorStreamChunk(StreamChunk):
    """An error occurred during streaming."""

    type: Literal["error"] = "error"
    data: Dict[str, Any] = Field(
        ..., description="Error data with code and message"
    )
